// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error)
	GetCategoriesByUser(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	GetExpensesByUser(ctx context.Context, arg GetExpensesByUserParams) ([]Expense, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	Ping(ctx context.Context) (int32, error)
	RevokeAllUserTokens(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error)
	UpdateCategorySortOrder(ctx context.Context, arg UpdateCategorySortOrderParams) error
}

var _ Querier = (*Queries)(nil)
