ALTER TABLE recipes DROP CONSTRAINT IF EXISTS recipes_nutrition_nonneg;
ALTER TABLE recipes DROP COLUMN IF EXISTS carbs_g;
ALTER TABLE recipes DROP COLUMN IF EXISTS fat_g;
ALTER TABLE recipes DROP COLUMN IF EXISTS protein_g;
ALTER TABLE recipes DROP COLUMN IF EXISTS kcal;
