ALTER TABLE recipes ADD COLUMN IF NOT EXISTS kcal      INT  NOT NULL DEFAULT 0;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS protein_g REAL NOT NULL DEFAULT 0;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS fat_g     REAL NOT NULL DEFAULT 0;
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS carbs_g   REAL NOT NULL DEFAULT 0;

DO $$
BEGIN
    ALTER TABLE recipes ADD CONSTRAINT recipes_nutrition_nonneg
        CHECK (kcal >= 0 AND protein_g >= 0 AND fat_g >= 0 AND carbs_g >= 0);
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;
