package com.example.noteapp.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    // Auth
    val welcomeBack: String,
    val signIn: String,
    val signInToContinue: String,
    val email: String,
    val password: String,
    val showPassword: String,
    val hidePassword: String,
    val dontHaveAccount: String,
    val createAccount: String,
    val joinUsToday: String,
    val getStarted: String,
    val createYourAccount: String,
    val username: String,
    val alreadyHaveAccount: String,
    // Lists
    val notesManager: String,
    val yourCollection: String,
    val myLists: String,
    val public: String,
    val logout: String,
    val newList: String,
    val noListsYet: String,
    val noPublicLists: String,
    val publicBadge: String,
    // List detail
    val addTag: String,
    val addTagHint: String,
    val noItemsYet: String,
    val addItem: String,
    val editItem: String,
    val typeText: String,
    val typeLink: String,
    val typeImage: String,
    val pickImage: String,
    val changeImage: String,
    val url: String,
    val textContent: String,
    val imageUrl: String,
    val save: String,
    val cancel: String,
    val add: String,
    // Create / Edit list
    val newListTitle: String,
    val editListTitle: String,
    val title: String,
    val description: String,
    val publicList: String,
    val anyoneCanView: String,
    val createList: String,
    val saveChanges: String,
    // Item actions
    val delete: String,
    val moveUp: String,
    val moveDown: String,
    // Settings
    val settings: String,
    val language: String,
    val languageEn: String,
    val languageUk: String,
    val accentColor: String,
)

val EnglishStrings = AppStrings(
    welcomeBack = "Welcome back",
    signIn = "Sign In",
    signInToContinue = "Sign in to continue",
    email = "Email",
    password = "Password",
    showPassword = "Show password",
    hidePassword = "Hide password",
    dontHaveAccount = "Don't have an account? Register",
    createAccount = "Create Account",
    joinUsToday = "Join us today",
    getStarted = "Get started",
    createYourAccount = "Create your free account",
    username = "Username",
    alreadyHaveAccount = "Already have an account? Sign in",
    notesManager = "Notes Manager",
    yourCollection = "Your personal collection",
    myLists = "My Lists",
    public = "Public",
    logout = "Logout",
    newList = "New List",
    noListsYet = "No lists yet. Create one!",
    noPublicLists = "No public lists available.",
    publicBadge = "Public",
    addTag = "+ Tag",
    addTagHint = "Tag name",
    noItemsYet = "No items yet. Tap + to add one.",
    addItem = "Add Item",
    editItem = "Edit Item",
    typeText = "TEXT",
    typeLink = "LINK",
    typeImage = "IMAGE",
    pickImage = "Pick Image from Gallery",
    changeImage = "Change Image",
    url = "URL",
    textContent = "Text content",
    imageUrl = "Image URL",
    save = "Save",
    cancel = "Cancel",
    add = "Add",
    newListTitle = "New List",
    editListTitle = "Edit List",
    title = "Title",
    description = "Description",
    publicList = "Public list",
    anyoneCanView = "Anyone can view this list",
    createList = "Create List",
    saveChanges = "Save Changes",
    delete = "Delete",
    moveUp = "Move up",
    moveDown = "Move down",
    settings = "Settings",
    language = "Language",
    languageEn = "English",
    languageUk = "Українська",
    accentColor = "Accent color",
)

val UkrainianStrings = AppStrings(
    welcomeBack = "Ласкаво просимо",
    signIn = "Увійти",
    signInToContinue = "Увійдіть, щоб продовжити",
    email = "Пошта",
    password = "Пароль",
    showPassword = "Показати пароль",
    hidePassword = "Сховати пароль",
    dontHaveAccount = "Немає акаунту? Зареєструватись",
    createAccount = "Створити акаунт",
    joinUsToday = "Приєднуйся сьогодні",
    getStarted = "Починаємо",
    createYourAccount = "Створіть безкоштовний акаунт",
    username = "Ім'я користувача",
    alreadyHaveAccount = "Вже є акаунт? Увійти",
    notesManager = "Менеджер нотаток",
    yourCollection = "Ваша особиста колекція",
    myLists = "Мої списки",
    public = "Публічні",
    logout = "Вийти",
    newList = "Новий список",
    noListsYet = "Списків ще немає. Створіть один!",
    noPublicLists = "Публічних списків немає.",
    publicBadge = "Публічний",
    addTag = "+ Тег",
    addTagHint = "Назва тегу",
    noItemsYet = "Елементів ще немає. Натисніть + щоб додати.",
    addItem = "Додати елемент",
    editItem = "Редагувати елемент",
    typeText = "ТЕКСТ",
    typeLink = "ПОСИЛАННЯ",
    typeImage = "ЗОБРАЖЕННЯ",
    pickImage = "Вибрати зображення",
    changeImage = "Змінити зображення",
    url = "URL",
    textContent = "Текстовий вміст",
    imageUrl = "URL зображення",
    save = "Зберегти",
    cancel = "Скасувати",
    add = "Додати",
    newListTitle = "Новий список",
    editListTitle = "Редагувати список",
    title = "Назва",
    description = "Опис",
    publicList = "Публічний список",
    anyoneCanView = "Будь-хто може переглянути",
    createList = "Створити список",
    saveChanges = "Зберегти зміни",
    delete = "Видалити",
    moveUp = "Перемістити вгору",
    moveDown = "Перемістити вниз",
    settings = "Налаштування",
    language = "Мова",
    languageEn = "English",
    languageUk = "Українська",
    accentColor = "Колір акценту",
)

val LocalStrings = staticCompositionLocalOf<AppStrings> { EnglishStrings }
