// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

@com.google.protobuf.Generated
public interface ActivityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notes.v1.Activity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string note_id = 2 [json_name = "noteId"];</code>
   * @return The noteId.
   */
  java.lang.String getNoteId();
  /**
   * <code>string note_id = 2 [json_name = "noteId"];</code>
   * @return The bytes for noteId.
   */
  com.google.protobuf.ByteString
      getNoteIdBytes();

  /**
   * <code>string actor_user_id = 3 [json_name = "actorUserId"];</code>
   * @return The actorUserId.
   */
  java.lang.String getActorUserId();
  /**
   * <code>string actor_user_id = 3 [json_name = "actorUserId"];</code>
   * @return The bytes for actorUserId.
   */
  com.google.protobuf.ByteString
      getActorUserIdBytes();

  /**
   * <code>.notes.v1.ActivityKind kind = 4 [json_name = "kind"];</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.notes.v1.ActivityKind kind = 4 [json_name = "kind"];</code>
   * @return The kind.
   */
  com.nnc.familymanager.notes.v1.ActivityKind getKind();

  /**
   * <code>string detail = 5 [json_name = "detail"];</code>
   * @return The detail.
   */
  java.lang.String getDetail();
  /**
   * <code>string detail = 5 [json_name = "detail"];</code>
   * @return The bytes for detail.
   */
  com.google.protobuf.ByteString
      getDetailBytes();

  /**
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
}
