// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

/**
 * Protobuf type {@code notes.v1.CreateNotebookResponse}
 */
@com.google.protobuf.Generated
public final class CreateNotebookResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:notes.v1.CreateNotebookResponse)
    CreateNotebookResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 2,
      /* suffix= */ "",
      "CreateNotebookResponse");
  }
  // Use CreateNotebookResponse.newBuilder() to construct.
  private CreateNotebookResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateNotebookResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_CreateNotebookResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_CreateNotebookResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_CreateNotebookResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nnc.familymanager.notes.v1.CreateNotebookResponse.class, com.nnc.familymanager.notes.v1.CreateNotebookResponse.Builder.class);
  }

  private int bitField0_;
  public static final int NOTEBOOK_FIELD_NUMBER = 1;
  private com.nnc.familymanager.notes.v1.Notebook notebook_;
  /**
   * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
   * @return Whether the notebook field is set.
   */
  @java.lang.Override
  public boolean hasNotebook() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
   * @return The notebook.
   */
  @java.lang.Override
  public com.nnc.familymanager.notes.v1.Notebook getNotebook() {
    return notebook_ == null ? com.nnc.familymanager.notes.v1.Notebook.getDefaultInstance() : notebook_;
  }
  /**
   * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
   */
  @java.lang.Override
  public com.nnc.familymanager.notes.v1.NotebookOrBuilder getNotebookOrBuilder() {
    return notebook_ == null ? com.nnc.familymanager.notes.v1.Notebook.getDefaultInstance() : notebook_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getNotebook());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNotebook());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nnc.familymanager.notes.v1.CreateNotebookResponse)) {
      return super.equals(obj);
    }
    com.nnc.familymanager.notes.v1.CreateNotebookResponse other = (com.nnc.familymanager.notes.v1.CreateNotebookResponse) obj;

    if (hasNotebook() != other.hasNotebook()) return false;
    if (hasNotebook()) {
      if (!getNotebook()
          .equals(other.getNotebook())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNotebook()) {
      hash = (37 * hash) + NOTEBOOK_FIELD_NUMBER;
      hash = (53 * hash) + getNotebook().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nnc.familymanager.notes.v1.CreateNotebookResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code notes.v1.CreateNotebookResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:notes.v1.CreateNotebookResponse)
      com.nnc.familymanager.notes.v1.CreateNotebookResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_CreateNotebookResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_CreateNotebookResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nnc.familymanager.notes.v1.CreateNotebookResponse.class, com.nnc.familymanager.notes.v1.CreateNotebookResponse.Builder.class);
    }

    // Construct using com.nnc.familymanager.notes.v1.CreateNotebookResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetNotebookFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      notebook_ = null;
      if (notebookBuilder_ != null) {
        notebookBuilder_.dispose();
        notebookBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_CreateNotebookResponse_descriptor;
    }

    @java.lang.Override
    public com.nnc.familymanager.notes.v1.CreateNotebookResponse getDefaultInstanceForType() {
      return com.nnc.familymanager.notes.v1.CreateNotebookResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.nnc.familymanager.notes.v1.CreateNotebookResponse build() {
      com.nnc.familymanager.notes.v1.CreateNotebookResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nnc.familymanager.notes.v1.CreateNotebookResponse buildPartial() {
      com.nnc.familymanager.notes.v1.CreateNotebookResponse result = new com.nnc.familymanager.notes.v1.CreateNotebookResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nnc.familymanager.notes.v1.CreateNotebookResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.notebook_ = notebookBuilder_ == null
            ? notebook_
            : notebookBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nnc.familymanager.notes.v1.CreateNotebookResponse) {
        return mergeFrom((com.nnc.familymanager.notes.v1.CreateNotebookResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nnc.familymanager.notes.v1.CreateNotebookResponse other) {
      if (other == com.nnc.familymanager.notes.v1.CreateNotebookResponse.getDefaultInstance()) return this;
      if (other.hasNotebook()) {
        mergeNotebook(other.getNotebook());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetNotebookFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.nnc.familymanager.notes.v1.Notebook notebook_;
    private com.google.protobuf.SingleFieldBuilder<
        com.nnc.familymanager.notes.v1.Notebook, com.nnc.familymanager.notes.v1.Notebook.Builder, com.nnc.familymanager.notes.v1.NotebookOrBuilder> notebookBuilder_;
    /**
     * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
     * @return Whether the notebook field is set.
     */
    public boolean hasNotebook() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
     * @return The notebook.
     */
    public com.nnc.familymanager.notes.v1.Notebook getNotebook() {
      if (notebookBuilder_ == null) {
        return notebook_ == null ? com.nnc.familymanager.notes.v1.Notebook.getDefaultInstance() : notebook_;
      } else {
        return notebookBuilder_.getMessage();
      }
    }
    /**
     * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
     */
    public Builder setNotebook(com.nnc.familymanager.notes.v1.Notebook value) {
      if (notebookBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        notebook_ = value;
      } else {
        notebookBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
     */
    public Builder setNotebook(
        com.nnc.familymanager.notes.v1.Notebook.Builder builderForValue) {
      if (notebookBuilder_ == null) {
        notebook_ = builderForValue.build();
      } else {
        notebookBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
     */
    public Builder mergeNotebook(com.nnc.familymanager.notes.v1.Notebook value) {
      if (notebookBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          notebook_ != null &&
          notebook_ != com.nnc.familymanager.notes.v1.Notebook.getDefaultInstance()) {
          getNotebookBuilder().mergeFrom(value);
        } else {
          notebook_ = value;
        }
      } else {
        notebookBuilder_.mergeFrom(value);
      }
      if (notebook_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
     */
    public Builder clearNotebook() {
      bitField0_ = (bitField0_ & ~0x00000001);
      notebook_ = null;
      if (notebookBuilder_ != null) {
        notebookBuilder_.dispose();
        notebookBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
     */
    public com.nnc.familymanager.notes.v1.Notebook.Builder getNotebookBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetNotebookFieldBuilder().getBuilder();
    }
    /**
     * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
     */
    public com.nnc.familymanager.notes.v1.NotebookOrBuilder getNotebookOrBuilder() {
      if (notebookBuilder_ != null) {
        return notebookBuilder_.getMessageOrBuilder();
      } else {
        return notebook_ == null ?
            com.nnc.familymanager.notes.v1.Notebook.getDefaultInstance() : notebook_;
      }
    }
    /**
     * <code>.notes.v1.Notebook notebook = 1 [json_name = "notebook"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.nnc.familymanager.notes.v1.Notebook, com.nnc.familymanager.notes.v1.Notebook.Builder, com.nnc.familymanager.notes.v1.NotebookOrBuilder> 
        internalGetNotebookFieldBuilder() {
      if (notebookBuilder_ == null) {
        notebookBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.nnc.familymanager.notes.v1.Notebook, com.nnc.familymanager.notes.v1.Notebook.Builder, com.nnc.familymanager.notes.v1.NotebookOrBuilder>(
                getNotebook(),
                getParentForChildren(),
                isClean());
        notebook_ = null;
      }
      return notebookBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:notes.v1.CreateNotebookResponse)
  }

  // @@protoc_insertion_point(class_scope:notes.v1.CreateNotebookResponse)
  private static final com.nnc.familymanager.notes.v1.CreateNotebookResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nnc.familymanager.notes.v1.CreateNotebookResponse();
  }

  public static com.nnc.familymanager.notes.v1.CreateNotebookResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateNotebookResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateNotebookResponse>() {
    @java.lang.Override
    public CreateNotebookResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateNotebookResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateNotebookResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nnc.familymanager.notes.v1.CreateNotebookResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

