// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

@com.google.protobuf.Generated
public interface DeleteNotebookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notes.v1.DeleteNotebookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string notebook_id = 1 [json_name = "notebookId"];</code>
   * @return The notebookId.
   */
  java.lang.String getNotebookId();
  /**
   * <code>string notebook_id = 1 [json_name = "notebookId"];</code>
   * @return The bytes for notebookId.
   */
  com.google.protobuf.ByteString
      getNotebookIdBytes();
}
