// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

@com.google.protobuf.Generated
public interface ListSharedWithMeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notes.v1.ListSharedWithMeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .notes.v1.Note notes = 1 [json_name = "notes"];</code>
   */
  java.util.List<com.nnc.familymanager.notes.v1.Note> 
      getNotesList();
  /**
   * <code>repeated .notes.v1.Note notes = 1 [json_name = "notes"];</code>
   */
  com.nnc.familymanager.notes.v1.Note getNotes(int index);
  /**
   * <code>repeated .notes.v1.Note notes = 1 [json_name = "notes"];</code>
   */
  int getNotesCount();
  /**
   * <code>repeated .notes.v1.Note notes = 1 [json_name = "notes"];</code>
   */
  java.util.List<? extends com.nnc.familymanager.notes.v1.NoteOrBuilder> 
      getNotesOrBuilderList();
  /**
   * <code>repeated .notes.v1.Note notes = 1 [json_name = "notes"];</code>
   */
  com.nnc.familymanager.notes.v1.NoteOrBuilder getNotesOrBuilder(
      int index);

  /**
   * <code>repeated .notes.v1.Notebook notebooks = 2 [json_name = "notebooks"];</code>
   */
  java.util.List<com.nnc.familymanager.notes.v1.Notebook> 
      getNotebooksList();
  /**
   * <code>repeated .notes.v1.Notebook notebooks = 2 [json_name = "notebooks"];</code>
   */
  com.nnc.familymanager.notes.v1.Notebook getNotebooks(int index);
  /**
   * <code>repeated .notes.v1.Notebook notebooks = 2 [json_name = "notebooks"];</code>
   */
  int getNotebooksCount();
  /**
   * <code>repeated .notes.v1.Notebook notebooks = 2 [json_name = "notebooks"];</code>
   */
  java.util.List<? extends com.nnc.familymanager.notes.v1.NotebookOrBuilder> 
      getNotebooksOrBuilderList();
  /**
   * <code>repeated .notes.v1.Notebook notebooks = 2 [json_name = "notebooks"];</code>
   */
  com.nnc.familymanager.notes.v1.NotebookOrBuilder getNotebooksOrBuilder(
      int index);
}
