// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

@com.google.protobuf.Generated
public interface ListActivityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notes.v1.ListActivityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .notes.v1.Activity activity = 1 [json_name = "activity"];</code>
   */
  java.util.List<com.nnc.familymanager.notes.v1.Activity> 
      getActivityList();
  /**
   * <code>repeated .notes.v1.Activity activity = 1 [json_name = "activity"];</code>
   */
  com.nnc.familymanager.notes.v1.Activity getActivity(int index);
  /**
   * <code>repeated .notes.v1.Activity activity = 1 [json_name = "activity"];</code>
   */
  int getActivityCount();
  /**
   * <code>repeated .notes.v1.Activity activity = 1 [json_name = "activity"];</code>
   */
  java.util.List<? extends com.nnc.familymanager.notes.v1.ActivityOrBuilder> 
      getActivityOrBuilderList();
  /**
   * <code>repeated .notes.v1.Activity activity = 1 [json_name = "activity"];</code>
   */
  com.nnc.familymanager.notes.v1.ActivityOrBuilder getActivityOrBuilder(
      int index);
}
