// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

@com.google.protobuf.Generated
public interface ListNotesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notes.v1.ListNotesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string notebook_id = 1 [json_name = "notebookId"];</code>
   * @return The notebookId.
   */
  java.lang.String getNotebookId();
  /**
   * <code>string notebook_id = 1 [json_name = "notebookId"];</code>
   * @return The bytes for notebookId.
   */
  com.google.protobuf.ByteString
      getNotebookIdBytes();

  /**
   * <code>bool starred_only = 2 [json_name = "starredOnly"];</code>
   * @return The starredOnly.
   */
  boolean getStarredOnly();

  /**
   * <code>bool include_archived = 3 [json_name = "includeArchived"];</code>
   * @return The includeArchived.
   */
  boolean getIncludeArchived();

  /**
   * <code>bool shared_only = 4 [json_name = "sharedOnly"];</code>
   * @return The sharedOnly.
   */
  boolean getSharedOnly();

  /**
   * <code>.notes.v1.NoteSort sort = 5 [json_name = "sort"];</code>
   * @return The enum numeric value on the wire for sort.
   */
  int getSortValue();
  /**
   * <code>.notes.v1.NoteSort sort = 5 [json_name = "sort"];</code>
   * @return The sort.
   */
  com.nnc.familymanager.notes.v1.NoteSort getSort();

  /**
   * <code>int32 page_size = 6 [json_name = "pageSize"];</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <code>bool archived_only = 7 [json_name = "archivedOnly"];</code>
   * @return The archivedOnly.
   */
  boolean getArchivedOnly();
}
