// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

@com.google.protobuf.Generated
public interface ListCommentsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notes.v1.ListCommentsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .notes.v1.Comment comments = 1 [json_name = "comments"];</code>
   */
  java.util.List<com.nnc.familymanager.notes.v1.Comment> 
      getCommentsList();
  /**
   * <code>repeated .notes.v1.Comment comments = 1 [json_name = "comments"];</code>
   */
  com.nnc.familymanager.notes.v1.Comment getComments(int index);
  /**
   * <code>repeated .notes.v1.Comment comments = 1 [json_name = "comments"];</code>
   */
  int getCommentsCount();
  /**
   * <code>repeated .notes.v1.Comment comments = 1 [json_name = "comments"];</code>
   */
  java.util.List<? extends com.nnc.familymanager.notes.v1.CommentOrBuilder> 
      getCommentsOrBuilderList();
  /**
   * <code>repeated .notes.v1.Comment comments = 1 [json_name = "comments"];</code>
   */
  com.nnc.familymanager.notes.v1.CommentOrBuilder getCommentsOrBuilder(
      int index);
}
