// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

/**
 * Protobuf type {@code notes.v1.Notebook}
 */
@com.google.protobuf.Generated
public final class Notebook extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:notes.v1.Notebook)
    NotebookOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 2,
      /* suffix= */ "",
      "Notebook");
  }
  // Use Notebook.newBuilder() to construct.
  private Notebook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Notebook() {
    id_ = "";
    familyId_ = "";
    ownerUserId_ = "";
    parentId_ = "";
    name_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_Notebook_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_Notebook_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_Notebook_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nnc.familymanager.notes.v1.Notebook.class, com.nnc.familymanager.notes.v1.Notebook.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAMILY_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object familyId_ = "";
  /**
   * <code>string family_id = 2 [json_name = "familyId"];</code>
   * @return The familyId.
   */
  @java.lang.Override
  public java.lang.String getFamilyId() {
    java.lang.Object ref = familyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      familyId_ = s;
      return s;
    }
  }
  /**
   * <code>string family_id = 2 [json_name = "familyId"];</code>
   * @return The bytes for familyId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFamilyIdBytes() {
    java.lang.Object ref = familyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      familyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_USER_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ownerUserId_ = "";
  /**
   * <code>string owner_user_id = 3 [json_name = "ownerUserId"];</code>
   * @return The ownerUserId.
   */
  @java.lang.Override
  public java.lang.String getOwnerUserId() {
    java.lang.Object ref = ownerUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownerUserId_ = s;
      return s;
    }
  }
  /**
   * <code>string owner_user_id = 3 [json_name = "ownerUserId"];</code>
   * @return The bytes for ownerUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerUserIdBytes() {
    java.lang.Object ref = ownerUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownerUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENT_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentId_ = "";
  /**
   * <code>string parent_id = 4 [json_name = "parentId"];</code>
   * @return The parentId.
   */
  @java.lang.Override
  public java.lang.String getParentId() {
    java.lang.Object ref = parentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentId_ = s;
      return s;
    }
  }
  /**
   * <code>string parent_id = 4 [json_name = "parentId"];</code>
   * @return The bytes for parentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentIdBytes() {
    java.lang.Object ref = parentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 5 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 5 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARCHIVED_FIELD_NUMBER = 6;
  private boolean archived_ = false;
  /**
   * <code>bool archived = 6 [json_name = "archived"];</code>
   * @return The archived.
   */
  @java.lang.Override
  public boolean getArchived() {
    return archived_;
  }

  public static final int NOTE_COUNT_FIELD_NUMBER = 7;
  private int noteCount_ = 0;
  /**
   * <code>int32 note_count = 7 [json_name = "noteCount"];</code>
   * @return The noteCount.
   */
  @java.lang.Override
  public int getNoteCount() {
    return noteCount_;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp updatedAt_;
  /**
   * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
   * @return Whether the updatedAt field is set.
   */
  @java.lang.Override
  public boolean hasUpdatedAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdatedAt() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(familyId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, familyId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ownerUserId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, ownerUserId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(parentId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, parentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, name_);
    }
    if (archived_ != false) {
      output.writeBool(6, archived_);
    }
    if (noteCount_ != 0) {
      output.writeInt32(7, noteCount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(8, getCreatedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(9, getUpdatedAt());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(familyId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, familyId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ownerUserId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, ownerUserId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(parentId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, parentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, name_);
    }
    if (archived_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, archived_);
    }
    if (noteCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, noteCount_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getCreatedAt());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getUpdatedAt());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nnc.familymanager.notes.v1.Notebook)) {
      return super.equals(obj);
    }
    com.nnc.familymanager.notes.v1.Notebook other = (com.nnc.familymanager.notes.v1.Notebook) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getFamilyId()
        .equals(other.getFamilyId())) return false;
    if (!getOwnerUserId()
        .equals(other.getOwnerUserId())) return false;
    if (!getParentId()
        .equals(other.getParentId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getArchived()
        != other.getArchived()) return false;
    if (getNoteCount()
        != other.getNoteCount()) return false;
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
    if (hasUpdatedAt()) {
      if (!getUpdatedAt()
          .equals(other.getUpdatedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + FAMILY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFamilyId().hashCode();
    hash = (37 * hash) + OWNER_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerUserId().hashCode();
    hash = (37 * hash) + PARENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getParentId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ARCHIVED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getArchived());
    hash = (37 * hash) + NOTE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getNoteCount();
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    if (hasUpdatedAt()) {
      hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nnc.familymanager.notes.v1.Notebook parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nnc.familymanager.notes.v1.Notebook parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.Notebook parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nnc.familymanager.notes.v1.Notebook parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.Notebook parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nnc.familymanager.notes.v1.Notebook parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.Notebook parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nnc.familymanager.notes.v1.Notebook parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nnc.familymanager.notes.v1.Notebook parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nnc.familymanager.notes.v1.Notebook parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.Notebook parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nnc.familymanager.notes.v1.Notebook parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nnc.familymanager.notes.v1.Notebook prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code notes.v1.Notebook}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:notes.v1.Notebook)
      com.nnc.familymanager.notes.v1.NotebookOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_Notebook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_Notebook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nnc.familymanager.notes.v1.Notebook.class, com.nnc.familymanager.notes.v1.Notebook.Builder.class);
    }

    // Construct using com.nnc.familymanager.notes.v1.Notebook.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCreatedAtFieldBuilder();
        internalGetUpdatedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      familyId_ = "";
      ownerUserId_ = "";
      parentId_ = "";
      name_ = "";
      archived_ = false;
      noteCount_ = 0;
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_Notebook_descriptor;
    }

    @java.lang.Override
    public com.nnc.familymanager.notes.v1.Notebook getDefaultInstanceForType() {
      return com.nnc.familymanager.notes.v1.Notebook.getDefaultInstance();
    }

    @java.lang.Override
    public com.nnc.familymanager.notes.v1.Notebook build() {
      com.nnc.familymanager.notes.v1.Notebook result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nnc.familymanager.notes.v1.Notebook buildPartial() {
      com.nnc.familymanager.notes.v1.Notebook result = new com.nnc.familymanager.notes.v1.Notebook(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nnc.familymanager.notes.v1.Notebook result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.familyId_ = familyId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ownerUserId_ = ownerUserId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.parentId_ = parentId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.archived_ = archived_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.noteCount_ = noteCount_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.updatedAt_ = updatedAtBuilder_ == null
            ? updatedAt_
            : updatedAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nnc.familymanager.notes.v1.Notebook) {
        return mergeFrom((com.nnc.familymanager.notes.v1.Notebook)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nnc.familymanager.notes.v1.Notebook other) {
      if (other == com.nnc.familymanager.notes.v1.Notebook.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFamilyId().isEmpty()) {
        familyId_ = other.familyId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getOwnerUserId().isEmpty()) {
        ownerUserId_ = other.ownerUserId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getParentId().isEmpty()) {
        parentId_ = other.parentId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getArchived() != false) {
        setArchived(other.getArchived());
      }
      if (other.getNoteCount() != 0) {
        setNoteCount(other.getNoteCount());
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (other.hasUpdatedAt()) {
        mergeUpdatedAt(other.getUpdatedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              familyId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ownerUserId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              parentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              archived_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              noteCount_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              input.readMessage(
                  internalGetCreatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  internalGetUpdatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object familyId_ = "";
    /**
     * <code>string family_id = 2 [json_name = "familyId"];</code>
     * @return The familyId.
     */
    public java.lang.String getFamilyId() {
      java.lang.Object ref = familyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        familyId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string family_id = 2 [json_name = "familyId"];</code>
     * @return The bytes for familyId.
     */
    public com.google.protobuf.ByteString
        getFamilyIdBytes() {
      java.lang.Object ref = familyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        familyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string family_id = 2 [json_name = "familyId"];</code>
     * @param value The familyId to set.
     * @return This builder for chaining.
     */
    public Builder setFamilyId(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      familyId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string family_id = 2 [json_name = "familyId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFamilyId() {
      familyId_ = getDefaultInstance().getFamilyId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string family_id = 2 [json_name = "familyId"];</code>
     * @param value The bytes for familyId to set.
     * @return This builder for chaining.
     */
    public Builder setFamilyIdBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      familyId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object ownerUserId_ = "";
    /**
     * <code>string owner_user_id = 3 [json_name = "ownerUserId"];</code>
     * @return The ownerUserId.
     */
    public java.lang.String getOwnerUserId() {
      java.lang.Object ref = ownerUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string owner_user_id = 3 [json_name = "ownerUserId"];</code>
     * @return The bytes for ownerUserId.
     */
    public com.google.protobuf.ByteString
        getOwnerUserIdBytes() {
      java.lang.Object ref = ownerUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string owner_user_id = 3 [json_name = "ownerUserId"];</code>
     * @param value The ownerUserId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerUserId(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      ownerUserId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string owner_user_id = 3 [json_name = "ownerUserId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerUserId() {
      ownerUserId_ = getDefaultInstance().getOwnerUserId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string owner_user_id = 3 [json_name = "ownerUserId"];</code>
     * @param value The bytes for ownerUserId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerUserIdBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      ownerUserId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object parentId_ = "";
    /**
     * <code>string parent_id = 4 [json_name = "parentId"];</code>
     * @return The parentId.
     */
    public java.lang.String getParentId() {
      java.lang.Object ref = parentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string parent_id = 4 [json_name = "parentId"];</code>
     * @return The bytes for parentId.
     */
    public com.google.protobuf.ByteString
        getParentIdBytes() {
      java.lang.Object ref = parentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parent_id = 4 [json_name = "parentId"];</code>
     * @param value The parentId to set.
     * @return This builder for chaining.
     */
    public Builder setParentId(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      parentId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string parent_id = 4 [json_name = "parentId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearParentId() {
      parentId_ = getDefaultInstance().getParentId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string parent_id = 4 [json_name = "parentId"];</code>
     * @param value The bytes for parentId to set.
     * @return This builder for chaining.
     */
    public Builder setParentIdBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      parentId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 5 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 5 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 5 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      name_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 5 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 5 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private boolean archived_ ;
    /**
     * <code>bool archived = 6 [json_name = "archived"];</code>
     * @return The archived.
     */
    @java.lang.Override
    public boolean getArchived() {
      return archived_;
    }
    /**
     * <code>bool archived = 6 [json_name = "archived"];</code>
     * @param value The archived to set.
     * @return This builder for chaining.
     */
    public Builder setArchived(boolean value) {

      archived_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool archived = 6 [json_name = "archived"];</code>
     * @return This builder for chaining.
     */
    public Builder clearArchived() {
      bitField0_ = (bitField0_ & ~0x00000020);
      archived_ = false;
      onChanged();
      return this;
    }

    private int noteCount_ ;
    /**
     * <code>int32 note_count = 7 [json_name = "noteCount"];</code>
     * @return The noteCount.
     */
    @java.lang.Override
    public int getNoteCount() {
      return noteCount_;
    }
    /**
     * <code>int32 note_count = 7 [json_name = "noteCount"];</code>
     * @param value The noteCount to set.
     * @return This builder for chaining.
     */
    public Builder setNoteCount(int value) {

      noteCount_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 note_count = 7 [json_name = "noteCount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNoteCount() {
      bitField0_ = (bitField0_ & ~0x00000040);
      noteCount_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      if (createdAt_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000080);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return internalGetCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 8 [json_name = "createdAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.Timestamp updatedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     * @return Whether the updatedAt field is set.
     */
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     * @return The updatedAt.
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      } else {
        return updatedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     */
    public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        updatedAt_ = value;
      } else {
        updatedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     */
    public Builder setUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = builderForValue.build();
      } else {
        updatedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     */
    public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          updatedAt_ != null &&
          updatedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getUpdatedAtBuilder().mergeFrom(value);
        } else {
          updatedAt_ = value;
        }
      } else {
        updatedAtBuilder_.mergeFrom(value);
      }
      if (updatedAt_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     */
    public Builder clearUpdatedAt() {
      bitField0_ = (bitField0_ & ~0x00000100);
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return internalGetUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      if (updatedAtBuilder_ != null) {
        return updatedAtBuilder_.getMessageOrBuilder();
      } else {
        return updatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updatedAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetUpdatedAtFieldBuilder() {
      if (updatedAtBuilder_ == null) {
        updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdatedAt(),
                getParentForChildren(),
                isClean());
        updatedAt_ = null;
      }
      return updatedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:notes.v1.Notebook)
  }

  // @@protoc_insertion_point(class_scope:notes.v1.Notebook)
  private static final com.nnc.familymanager.notes.v1.Notebook DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nnc.familymanager.notes.v1.Notebook();
  }

  public static com.nnc.familymanager.notes.v1.Notebook getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Notebook>
      PARSER = new com.google.protobuf.AbstractParser<Notebook>() {
    @java.lang.Override
    public Notebook parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Notebook> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Notebook> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nnc.familymanager.notes.v1.Notebook getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

