// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

@com.google.protobuf.Generated
public interface ResolveCommentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notes.v1.ResolveCommentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string comment_id = 1 [json_name = "commentId"];</code>
   * @return The commentId.
   */
  java.lang.String getCommentId();
  /**
   * <code>string comment_id = 1 [json_name = "commentId"];</code>
   * @return The bytes for commentId.
   */
  com.google.protobuf.ByteString
      getCommentIdBytes();

  /**
   * <code>bool resolved = 2 [json_name = "resolved"];</code>
   * @return The resolved.
   */
  boolean getResolved();
}
