// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

/**
 * Protobuf enum {@code notes.v1.SharePermission}
 */
@com.google.protobuf.Generated
public enum SharePermission
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SHARE_PERMISSION_UNSPECIFIED = 0;</code>
   */
  SHARE_PERMISSION_UNSPECIFIED(0),
  /**
   * <code>SHARE_PERMISSION_VIEW = 1;</code>
   */
  SHARE_PERMISSION_VIEW(1),
  /**
   * <code>SHARE_PERMISSION_EDIT = 2;</code>
   */
  SHARE_PERMISSION_EDIT(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 2,
      /* suffix= */ "",
      "SharePermission");
  }
  /**
   * <code>SHARE_PERMISSION_UNSPECIFIED = 0;</code>
   */
  public static final int SHARE_PERMISSION_UNSPECIFIED_VALUE = 0;
  /**
   * <code>SHARE_PERMISSION_VIEW = 1;</code>
   */
  public static final int SHARE_PERMISSION_VIEW_VALUE = 1;
  /**
   * <code>SHARE_PERMISSION_EDIT = 2;</code>
   */
  public static final int SHARE_PERMISSION_EDIT_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SharePermission valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SharePermission forNumber(int value) {
    switch (value) {
      case 0: return SHARE_PERMISSION_UNSPECIFIED;
      case 1: return SHARE_PERMISSION_VIEW;
      case 2: return SHARE_PERMISSION_EDIT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SharePermission>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SharePermission> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SharePermission>() {
          public SharePermission findValueByNumber(int number) {
            return SharePermission.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.nnc.familymanager.notes.v1.NotesProto.getDescriptor().getEnumType(1);
  }

  private static final SharePermission[] VALUES = values();

  public static SharePermission valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SharePermission(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:notes.v1.SharePermission)
}

