// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

/**
 * Protobuf type {@code notes.v1.ShareNotebookRequest}
 */
@com.google.protobuf.Generated
public final class ShareNotebookRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:notes.v1.ShareNotebookRequest)
    ShareNotebookRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 2,
      /* suffix= */ "",
      "ShareNotebookRequest");
  }
  // Use ShareNotebookRequest.newBuilder() to construct.
  private ShareNotebookRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ShareNotebookRequest() {
    notebookId_ = "";
    subject_ = 0;
    memberUserId_ = "";
    permission_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_ShareNotebookRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_ShareNotebookRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_ShareNotebookRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.nnc.familymanager.notes.v1.ShareNotebookRequest.class, com.nnc.familymanager.notes.v1.ShareNotebookRequest.Builder.class);
  }

  public static final int NOTEBOOK_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object notebookId_ = "";
  /**
   * <code>string notebook_id = 1 [json_name = "notebookId"];</code>
   * @return The notebookId.
   */
  @java.lang.Override
  public java.lang.String getNotebookId() {
    java.lang.Object ref = notebookId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notebookId_ = s;
      return s;
    }
  }
  /**
   * <code>string notebook_id = 1 [json_name = "notebookId"];</code>
   * @return The bytes for notebookId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNotebookIdBytes() {
    java.lang.Object ref = notebookId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      notebookId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBJECT_FIELD_NUMBER = 2;
  private int subject_ = 0;
  /**
   * <code>.notes.v1.ShareSubject subject = 2 [json_name = "subject"];</code>
   * @return The enum numeric value on the wire for subject.
   */
  @java.lang.Override public int getSubjectValue() {
    return subject_;
  }
  /**
   * <code>.notes.v1.ShareSubject subject = 2 [json_name = "subject"];</code>
   * @return The subject.
   */
  @java.lang.Override public com.nnc.familymanager.notes.v1.ShareSubject getSubject() {
    com.nnc.familymanager.notes.v1.ShareSubject result = com.nnc.familymanager.notes.v1.ShareSubject.forNumber(subject_);
    return result == null ? com.nnc.familymanager.notes.v1.ShareSubject.UNRECOGNIZED : result;
  }

  public static final int MEMBER_USER_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object memberUserId_ = "";
  /**
   * <code>string member_user_id = 3 [json_name = "memberUserId"];</code>
   * @return The memberUserId.
   */
  @java.lang.Override
  public java.lang.String getMemberUserId() {
    java.lang.Object ref = memberUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      memberUserId_ = s;
      return s;
    }
  }
  /**
   * <code>string member_user_id = 3 [json_name = "memberUserId"];</code>
   * @return The bytes for memberUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMemberUserIdBytes() {
    java.lang.Object ref = memberUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      memberUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERMISSION_FIELD_NUMBER = 4;
  private int permission_ = 0;
  /**
   * <code>.notes.v1.SharePermission permission = 4 [json_name = "permission"];</code>
   * @return The enum numeric value on the wire for permission.
   */
  @java.lang.Override public int getPermissionValue() {
    return permission_;
  }
  /**
   * <code>.notes.v1.SharePermission permission = 4 [json_name = "permission"];</code>
   * @return The permission.
   */
  @java.lang.Override public com.nnc.familymanager.notes.v1.SharePermission getPermission() {
    com.nnc.familymanager.notes.v1.SharePermission result = com.nnc.familymanager.notes.v1.SharePermission.forNumber(permission_);
    return result == null ? com.nnc.familymanager.notes.v1.SharePermission.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(notebookId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, notebookId_);
    }
    if (subject_ != com.nnc.familymanager.notes.v1.ShareSubject.SHARE_SUBJECT_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, subject_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(memberUserId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, memberUserId_);
    }
    if (permission_ != com.nnc.familymanager.notes.v1.SharePermission.SHARE_PERMISSION_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, permission_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(notebookId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, notebookId_);
    }
    if (subject_ != com.nnc.familymanager.notes.v1.ShareSubject.SHARE_SUBJECT_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, subject_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(memberUserId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, memberUserId_);
    }
    if (permission_ != com.nnc.familymanager.notes.v1.SharePermission.SHARE_PERMISSION_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, permission_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.nnc.familymanager.notes.v1.ShareNotebookRequest)) {
      return super.equals(obj);
    }
    com.nnc.familymanager.notes.v1.ShareNotebookRequest other = (com.nnc.familymanager.notes.v1.ShareNotebookRequest) obj;

    if (!getNotebookId()
        .equals(other.getNotebookId())) return false;
    if (subject_ != other.subject_) return false;
    if (!getMemberUserId()
        .equals(other.getMemberUserId())) return false;
    if (permission_ != other.permission_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NOTEBOOK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getNotebookId().hashCode();
    hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
    hash = (53 * hash) + subject_;
    hash = (37 * hash) + MEMBER_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMemberUserId().hashCode();
    hash = (37 * hash) + PERMISSION_FIELD_NUMBER;
    hash = (53 * hash) + permission_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.nnc.familymanager.notes.v1.ShareNotebookRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code notes.v1.ShareNotebookRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:notes.v1.ShareNotebookRequest)
      com.nnc.familymanager.notes.v1.ShareNotebookRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_ShareNotebookRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_ShareNotebookRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nnc.familymanager.notes.v1.ShareNotebookRequest.class, com.nnc.familymanager.notes.v1.ShareNotebookRequest.Builder.class);
    }

    // Construct using com.nnc.familymanager.notes.v1.ShareNotebookRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      notebookId_ = "";
      subject_ = 0;
      memberUserId_ = "";
      permission_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.nnc.familymanager.notes.v1.NotesProto.internal_static_notes_v1_ShareNotebookRequest_descriptor;
    }

    @java.lang.Override
    public com.nnc.familymanager.notes.v1.ShareNotebookRequest getDefaultInstanceForType() {
      return com.nnc.familymanager.notes.v1.ShareNotebookRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.nnc.familymanager.notes.v1.ShareNotebookRequest build() {
      com.nnc.familymanager.notes.v1.ShareNotebookRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.nnc.familymanager.notes.v1.ShareNotebookRequest buildPartial() {
      com.nnc.familymanager.notes.v1.ShareNotebookRequest result = new com.nnc.familymanager.notes.v1.ShareNotebookRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.nnc.familymanager.notes.v1.ShareNotebookRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.notebookId_ = notebookId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.subject_ = subject_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.memberUserId_ = memberUserId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.permission_ = permission_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.nnc.familymanager.notes.v1.ShareNotebookRequest) {
        return mergeFrom((com.nnc.familymanager.notes.v1.ShareNotebookRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.nnc.familymanager.notes.v1.ShareNotebookRequest other) {
      if (other == com.nnc.familymanager.notes.v1.ShareNotebookRequest.getDefaultInstance()) return this;
      if (!other.getNotebookId().isEmpty()) {
        notebookId_ = other.notebookId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.subject_ != 0) {
        setSubjectValue(other.getSubjectValue());
      }
      if (!other.getMemberUserId().isEmpty()) {
        memberUserId_ = other.memberUserId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.permission_ != 0) {
        setPermissionValue(other.getPermissionValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              notebookId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              subject_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              memberUserId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              permission_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object notebookId_ = "";
    /**
     * <code>string notebook_id = 1 [json_name = "notebookId"];</code>
     * @return The notebookId.
     */
    public java.lang.String getNotebookId() {
      java.lang.Object ref = notebookId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notebookId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string notebook_id = 1 [json_name = "notebookId"];</code>
     * @return The bytes for notebookId.
     */
    public com.google.protobuf.ByteString
        getNotebookIdBytes() {
      java.lang.Object ref = notebookId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        notebookId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string notebook_id = 1 [json_name = "notebookId"];</code>
     * @param value The notebookId to set.
     * @return This builder for chaining.
     */
    public Builder setNotebookId(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      notebookId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string notebook_id = 1 [json_name = "notebookId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNotebookId() {
      notebookId_ = getDefaultInstance().getNotebookId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string notebook_id = 1 [json_name = "notebookId"];</code>
     * @param value The bytes for notebookId to set.
     * @return This builder for chaining.
     */
    public Builder setNotebookIdBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      notebookId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int subject_ = 0;
    /**
     * <code>.notes.v1.ShareSubject subject = 2 [json_name = "subject"];</code>
     * @return The enum numeric value on the wire for subject.
     */
    @java.lang.Override public int getSubjectValue() {
      return subject_;
    }
    /**
     * <code>.notes.v1.ShareSubject subject = 2 [json_name = "subject"];</code>
     * @param value The enum numeric value on the wire for subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectValue(int value) {
      subject_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.notes.v1.ShareSubject subject = 2 [json_name = "subject"];</code>
     * @return The subject.
     */
    @java.lang.Override
    public com.nnc.familymanager.notes.v1.ShareSubject getSubject() {
      com.nnc.familymanager.notes.v1.ShareSubject result = com.nnc.familymanager.notes.v1.ShareSubject.forNumber(subject_);
      return result == null ? com.nnc.familymanager.notes.v1.ShareSubject.UNRECOGNIZED : result;
    }
    /**
     * <code>.notes.v1.ShareSubject subject = 2 [json_name = "subject"];</code>
     * @param value The subject to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setSubject(com.nnc.familymanager.notes.v1.ShareSubject value) {
      java.util.Objects.requireNonNull(value);
      bitField0_ |= 0x00000002;
      subject_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.notes.v1.ShareSubject subject = 2 [json_name = "subject"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSubject() {
      bitField0_ = (bitField0_ & ~0x00000002);
      subject_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object memberUserId_ = "";
    /**
     * <code>string member_user_id = 3 [json_name = "memberUserId"];</code>
     * @return The memberUserId.
     */
    public java.lang.String getMemberUserId() {
      java.lang.Object ref = memberUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memberUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string member_user_id = 3 [json_name = "memberUserId"];</code>
     * @return The bytes for memberUserId.
     */
    public com.google.protobuf.ByteString
        getMemberUserIdBytes() {
      java.lang.Object ref = memberUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memberUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string member_user_id = 3 [json_name = "memberUserId"];</code>
     * @param value The memberUserId to set.
     * @return This builder for chaining.
     */
    public Builder setMemberUserId(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      memberUserId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string member_user_id = 3 [json_name = "memberUserId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMemberUserId() {
      memberUserId_ = getDefaultInstance().getMemberUserId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string member_user_id = 3 [json_name = "memberUserId"];</code>
     * @param value The bytes for memberUserId to set.
     * @return This builder for chaining.
     */
    public Builder setMemberUserIdBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      memberUserId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int permission_ = 0;
    /**
     * <code>.notes.v1.SharePermission permission = 4 [json_name = "permission"];</code>
     * @return The enum numeric value on the wire for permission.
     */
    @java.lang.Override public int getPermissionValue() {
      return permission_;
    }
    /**
     * <code>.notes.v1.SharePermission permission = 4 [json_name = "permission"];</code>
     * @param value The enum numeric value on the wire for permission to set.
     * @return This builder for chaining.
     */
    public Builder setPermissionValue(int value) {
      permission_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.notes.v1.SharePermission permission = 4 [json_name = "permission"];</code>
     * @return The permission.
     */
    @java.lang.Override
    public com.nnc.familymanager.notes.v1.SharePermission getPermission() {
      com.nnc.familymanager.notes.v1.SharePermission result = com.nnc.familymanager.notes.v1.SharePermission.forNumber(permission_);
      return result == null ? com.nnc.familymanager.notes.v1.SharePermission.UNRECOGNIZED : result;
    }
    /**
     * <code>.notes.v1.SharePermission permission = 4 [json_name = "permission"];</code>
     * @param value The permission to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setPermission(com.nnc.familymanager.notes.v1.SharePermission value) {
      java.util.Objects.requireNonNull(value);
      bitField0_ |= 0x00000008;
      permission_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.notes.v1.SharePermission permission = 4 [json_name = "permission"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPermission() {
      bitField0_ = (bitField0_ & ~0x00000008);
      permission_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:notes.v1.ShareNotebookRequest)
  }

  // @@protoc_insertion_point(class_scope:notes.v1.ShareNotebookRequest)
  private static final com.nnc.familymanager.notes.v1.ShareNotebookRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.nnc.familymanager.notes.v1.ShareNotebookRequest();
  }

  public static com.nnc.familymanager.notes.v1.ShareNotebookRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShareNotebookRequest>
      PARSER = new com.google.protobuf.AbstractParser<ShareNotebookRequest>() {
    @java.lang.Override
    public ShareNotebookRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ShareNotebookRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShareNotebookRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.nnc.familymanager.notes.v1.ShareNotebookRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

