// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

@com.google.protobuf.Generated
public interface ShareOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notes.v1.Share)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.notes.v1.ShareSubject subject = 2 [json_name = "subject"];</code>
   * @return The enum numeric value on the wire for subject.
   */
  int getSubjectValue();
  /**
   * <code>.notes.v1.ShareSubject subject = 2 [json_name = "subject"];</code>
   * @return The subject.
   */
  com.nnc.familymanager.notes.v1.ShareSubject getSubject();

  /**
   * <code>string member_user_id = 3 [json_name = "memberUserId"];</code>
   * @return The memberUserId.
   */
  java.lang.String getMemberUserId();
  /**
   * <code>string member_user_id = 3 [json_name = "memberUserId"];</code>
   * @return The bytes for memberUserId.
   */
  com.google.protobuf.ByteString
      getMemberUserIdBytes();

  /**
   * <code>.notes.v1.SharePermission permission = 4 [json_name = "permission"];</code>
   * @return The enum numeric value on the wire for permission.
   */
  int getPermissionValue();
  /**
   * <code>.notes.v1.SharePermission permission = 4 [json_name = "permission"];</code>
   * @return The permission.
   */
  com.nnc.familymanager.notes.v1.SharePermission getPermission();

  /**
   * <code>string granted_by_user_id = 5 [json_name = "grantedByUserId"];</code>
   * @return The grantedByUserId.
   */
  java.lang.String getGrantedByUserId();
  /**
   * <code>string granted_by_user_id = 5 [json_name = "grantedByUserId"];</code>
   * @return The bytes for grantedByUserId.
   */
  com.google.protobuf.ByteString
      getGrantedByUserIdBytes();

  /**
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 6 [json_name = "createdAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
}
