// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

@com.google.protobuf.Generated
public interface ShareNoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notes.v1.ShareNoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string note_id = 1 [json_name = "noteId"];</code>
   * @return The noteId.
   */
  java.lang.String getNoteId();
  /**
   * <code>string note_id = 1 [json_name = "noteId"];</code>
   * @return The bytes for noteId.
   */
  com.google.protobuf.ByteString
      getNoteIdBytes();

  /**
   * <code>.notes.v1.ShareSubject subject = 2 [json_name = "subject"];</code>
   * @return The enum numeric value on the wire for subject.
   */
  int getSubjectValue();
  /**
   * <code>.notes.v1.ShareSubject subject = 2 [json_name = "subject"];</code>
   * @return The subject.
   */
  com.nnc.familymanager.notes.v1.ShareSubject getSubject();

  /**
   * <code>string member_user_id = 3 [json_name = "memberUserId"];</code>
   * @return The memberUserId.
   */
  java.lang.String getMemberUserId();
  /**
   * <code>string member_user_id = 3 [json_name = "memberUserId"];</code>
   * @return The bytes for memberUserId.
   */
  com.google.protobuf.ByteString
      getMemberUserIdBytes();

  /**
   * <code>.notes.v1.SharePermission permission = 4 [json_name = "permission"];</code>
   * @return The enum numeric value on the wire for permission.
   */
  int getPermissionValue();
  /**
   * <code>.notes.v1.SharePermission permission = 4 [json_name = "permission"];</code>
   * @return The permission.
   */
  com.nnc.familymanager.notes.v1.SharePermission getPermission();
}
