// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

@com.google.protobuf.Generated
public interface UnshareResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notes.v1.UnshareResponse)
    com.google.protobuf.MessageOrBuilder {
}
