// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notes/v1/notes.proto
// Protobuf Java Version: 4.36.2

package com.nnc.familymanager.notes.v1;

@com.google.protobuf.Generated
public interface UpdateNoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notes.v1.UpdateNoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string note_id = 1 [json_name = "noteId"];</code>
   * @return The noteId.
   */
  java.lang.String getNoteId();
  /**
   * <code>string note_id = 1 [json_name = "noteId"];</code>
   * @return The bytes for noteId.
   */
  com.google.protobuf.ByteString
      getNoteIdBytes();

  /**
   * <code>string title = 2 [json_name = "title"];</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>repeated .notes.v1.Block blocks = 3 [json_name = "blocks"];</code>
   */
  java.util.List<com.nnc.familymanager.notes.v1.Block> 
      getBlocksList();
  /**
   * <code>repeated .notes.v1.Block blocks = 3 [json_name = "blocks"];</code>
   */
  com.nnc.familymanager.notes.v1.Block getBlocks(int index);
  /**
   * <code>repeated .notes.v1.Block blocks = 3 [json_name = "blocks"];</code>
   */
  int getBlocksCount();
  /**
   * <code>repeated .notes.v1.Block blocks = 3 [json_name = "blocks"];</code>
   */
  java.util.List<? extends com.nnc.familymanager.notes.v1.BlockOrBuilder> 
      getBlocksOrBuilderList();
  /**
   * <code>repeated .notes.v1.Block blocks = 3 [json_name = "blocks"];</code>
   */
  com.nnc.familymanager.notes.v1.BlockOrBuilder getBlocksOrBuilder(
      int index);

  /**
   * <code>int64 expected_version = 4 [json_name = "expectedVersion"];</code>
   * @return The expectedVersion.
   */
  long getExpectedVersion();
}
