version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - forcetypeassert
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - contextcheck
    - noctx
    - errorlint
    - govet
    - unconvert
    - unused
    - copyloopvar

  exclusions:
    rules:
      - path: _test\.go
        linters: [noctx]

  settings:
    errcheck:
      check-blank: false
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    staticcheck:
      checks:
        - all
        - -ST1000

formatters:
  enable:
    - gofmt
