services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    expose:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    command: >
      sh -c "until psql -h localhost -U ${POSTGRES_USER} -d postgres -c 'select 1'; do
        echo 'Waiting for database to start...';
        sleep 2;
      done;
      psql -h localhost -U ${POSTGRES_USER} -d postgres -c 'CREATE DATABASE IF NOT EXISTS ${SHOPPING_DB};'"

  service-shopping:
    container_name: service-shopping
    build:
      context: ./apps/service-shopping
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${SHOPPING_DB}
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
