// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, icon, color, sort_order)
VALUES ($1, $2, $3, $4, (SELECT COALESCE(MAX(sort_order), -1) + 1 FROM categories WHERE user_id = $1))
RETURNING id, user_id, name, icon, color, sort_order, created_at, updated_at
`

type CreateCategoryParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Icon   string      `json:"icon"`
	Color  string      `json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories
WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategoriesByUser = `-- name: GetCategoriesByUser :many
SELECT id, user_id, name, icon, color, sort_order, created_at, updated_at
FROM categories
WHERE user_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) GetCategoriesByUser(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, user_id, name, icon, color, sort_order, created_at, updated_at
FROM categories
WHERE id = $1 AND user_id = $2
`

type GetCategoryByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :execrows
UPDATE categories
SET name = $3, icon = $4, color = $5, updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type UpdateCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Icon   string      `json:"icon"`
	Color  string      `json:"color"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.Color,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCategorySortOrder = `-- name: UpdateCategorySortOrder :exec
UPDATE categories
SET sort_order = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type UpdateCategorySortOrderParams struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpdateCategorySortOrder(ctx context.Context, arg UpdateCategorySortOrderParams) error {
	_, err := q.db.Exec(ctx, updateCategorySortOrder, arg.ID, arg.UserID, arg.SortOrder)
	return err
}
