// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meal_plan.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMealPlan = `-- name: ListMealPlan :many
SELECT id, family_id, recipe_id, plan_date, slot, servings, created_at FROM meal_plan_entries
WHERE family_id = $1
  AND plan_date >= $2
  AND plan_date <= $3
ORDER BY plan_date, slot
`

type ListMealPlanParams struct {
	FamilyID   pgtype.UUID
	PlanDate   pgtype.Date
	PlanDate_2 pgtype.Date
}

func (q *Queries) ListMealPlan(ctx context.Context, arg ListMealPlanParams) ([]MealPlanEntry, error) {
	rows, err := q.db.Query(ctx, listMealPlan, arg.FamilyID, arg.PlanDate, arg.PlanDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealPlanEntry
	for rows.Next() {
		var i MealPlanEntry
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.RecipeID,
			&i.PlanDate,
			&i.Slot,
			&i.Servings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planMeal = `-- name: PlanMeal :one
INSERT INTO meal_plan_entries (family_id, recipe_id, plan_date, slot, servings)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (family_id, plan_date, slot) DO UPDATE
    SET recipe_id = EXCLUDED.recipe_id, servings = EXCLUDED.servings
RETURNING id, family_id, recipe_id, plan_date, slot, servings, created_at
`

type PlanMealParams struct {
	FamilyID pgtype.UUID
	RecipeID pgtype.UUID
	PlanDate pgtype.Date
	Slot     string
	Servings int32
}

func (q *Queries) PlanMeal(ctx context.Context, arg PlanMealParams) (MealPlanEntry, error) {
	row := q.db.QueryRow(ctx, planMeal,
		arg.FamilyID,
		arg.RecipeID,
		arg.PlanDate,
		arg.Slot,
		arg.Servings,
	)
	var i MealPlanEntry
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.RecipeID,
		&i.PlanDate,
		&i.Slot,
		&i.Servings,
		&i.CreatedAt,
	)
	return i, err
}

const removeMealPlanEntry = `-- name: RemoveMealPlanEntry :execrows
DELETE FROM meal_plan_entries
WHERE id = $1 AND family_id = $2
`

type RemoveMealPlanEntryParams struct {
	ID       pgtype.UUID
	FamilyID pgtype.UUID
}

func (q *Queries) RemoveMealPlanEntry(ctx context.Context, arg RemoveMealPlanEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMealPlanEntry, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumIngredientsForBasket = `-- name: SumIngredientsForBasket :many
WITH ids AS (
    SELECT t.recipe_id, t.ord
    FROM unnest($1::uuid[]) WITH ORDINALITY AS t(recipe_id, ord)
), servs AS (
    SELECT t.servings, t.ord
    FROM unnest($2::int[]) WITH ORDINALITY AS t(servings, ord)
), basket AS (
    SELECT ids.recipe_id, servs.servings
    FROM ids JOIN servs ON servs.ord = ids.ord
), scaled AS (
    SELECT
        lower(btrim(ri.name)) AS name,
        lower(btrim(ri.unit)) AS unit,
        CASE
            WHEN b.servings = 0 THEN 1.0
            ELSE b.servings::numeric / NULLIF(r.servings, 0)
        END AS scale,
        ri.amount
    FROM basket b
    JOIN recipes r ON r.id = b.recipe_id AND r.family_id = $3
    JOIN recipe_ingredients ri ON ri.recipe_id = r.id
)
SELECT
    name,
    unit,
    COALESCE(
        SUM(CASE
            WHEN amount ~ '^[0-9]+(\.[0-9]+)?$'
            THEN amount::numeric * scale
            ELSE 1
        END),
        0
    )::text AS total_amount
FROM scaled
GROUP BY name, unit
ORDER BY name, unit
`

type SumIngredientsForBasketParams struct {
	RecipeIds    []pgtype.UUID
	ServingsList []int32
	FamilyID     pgtype.UUID
}

type SumIngredientsForBasketRow struct {
	Name        string
	Unit        string
	TotalAmount string
}

// SumIngredientsForBasket answers the ad-hoc question ("I plan to cook these, what do I
// buy") without persisting anything: the basket arrives as two parallel arrays and is
// unnested into rows. Same scaling and same name+unit grouping as TotalIngredients, so the
// calendar and the basket produce identical lines for identical input. The family_id join
// condition is what stops a caller totalling another family's recipes by id.
// The two arrays are unnested separately and re-joined on ordinality rather than with the
// two-argument unnest(a, b) form, which sqlc's query analyser cannot type.
func (q *Queries) SumIngredientsForBasket(ctx context.Context, arg SumIngredientsForBasketParams) ([]SumIngredientsForBasketRow, error) {
	rows, err := q.db.Query(ctx, sumIngredientsForBasket, arg.RecipeIds, arg.ServingsList, arg.FamilyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumIngredientsForBasketRow
	for rows.Next() {
		var i SumIngredientsForBasketRow
		if err := rows.Scan(&i.Name, &i.Unit, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalIngredients = `-- name: TotalIngredients :many
WITH scaled AS (
    SELECT
        lower(btrim(ri.name)) AS name,
        lower(btrim(ri.unit)) AS unit,
        CASE
            WHEN m.servings = 0 THEN 1.0
            ELSE m.servings::numeric / NULLIF(r.servings, 0)
        END AS scale,
        ri.amount
    FROM meal_plan_entries m
    JOIN recipes r ON r.id = m.recipe_id
    JOIN recipe_ingredients ri ON ri.recipe_id = m.recipe_id
    WHERE m.family_id = $1
      AND m.plan_date >= $2
      AND m.plan_date <= $3
)
SELECT
    name,
    unit,
    COALESCE(
        SUM(CASE
            WHEN amount ~ '^[0-9]+(\.[0-9]+)?$'
            THEN amount::numeric * scale
            ELSE 1
        END),
        0
    )::text AS total_amount
FROM scaled
GROUP BY name, unit
ORDER BY name, unit
`

type TotalIngredientsParams struct {
	FamilyID   pgtype.UUID
	PlanDate   pgtype.Date
	PlanDate_2 pgtype.Date
}

type TotalIngredientsRow struct {
	Name        string
	Unit        string
	TotalAmount string
}

// TotalIngredients: aggregates every ingredient across the meal plan range, scaled by each
// entry's servings relative to its recipe's servings. Sums by name+unit so "flour / g" from
// two recipes adds to one line on the shopping list. The amount is summed as numeric text
// (recipes store free-form amounts); non-numeric amounts are summed as count (1 per row) so
// "2 cloves" + "3 cloves" becomes "2" — the app shows the breakdown for non-numeric totals.
func (q *Queries) TotalIngredients(ctx context.Context, arg TotalIngredientsParams) ([]TotalIngredientsRow, error) {
	rows, err := q.db.Query(ctx, totalIngredients, arg.FamilyID, arg.PlanDate, arg.PlanDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalIngredientsRow
	for rows.Next() {
		var i TotalIngredientsRow
		if err := rows.Scan(&i.Name, &i.Unit, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
