// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MealPlanEntry struct {
	ID        pgtype.UUID
	FamilyID  pgtype.UUID
	RecipeID  pgtype.UUID
	PlanDate  pgtype.Date
	Slot      string
	Servings  int32
	CreatedAt pgtype.Timestamptz
}

type Recipe struct {
	ID            pgtype.UUID
	FamilyID      pgtype.UUID
	Title         string
	Description   string
	CategoryID    pgtype.UUID
	SubcategoryID pgtype.UUID
	Servings      int32
	PrepSeconds   int32
	CookSeconds   int32
	AuthorUserID  pgtype.UUID
	FavoriteCount int32
	CommentCount  int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ImageUrl      string
	Rating        int16
	Notes         string
}

type RecipeCategory struct {
	ID        pgtype.UUID
	FamilyID  pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type RecipeComment struct {
	ID        pgtype.UUID
	RecipeID  pgtype.UUID
	UserID    pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

type RecipeFavorite struct {
	RecipeID  pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type RecipeIngredient struct {
	RecipeID pgtype.UUID
	Position int32
	Name     string
	Amount   string
	Unit     string
}

type RecipeStep struct {
	RecipeID        pgtype.UUID
	Position        int32
	Instruction     string
	DurationSeconds int32
}

type RecipeSubcategory struct {
	ID         pgtype.UUID
	CategoryID pgtype.UUID
	FamilyID   pgtype.UUID
	Name       string
	CreatedAt  pgtype.Timestamptz
}
