// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (list_id, type, content, position)
VALUES ($1, $2, $3, $4)
RETURNING id, list_id, type, content, position, created_at, updated_at
`

type CreateItemParams struct {
	ListID   pgtype.UUID `json:"list_id"`
	Type     ItemType    `json:"type"`
	Content  string      `json:"content"`
	Position int32       `json:"position"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ListID,
		arg.Type,
		arg.Content,
		arg.Position,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Type,
		&i.Content,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, list_id, type, content, position, created_at, updated_at FROM items WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id pgtype.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Type,
		&i.Content,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemsByList = `-- name: GetItemsByList :many
SELECT id, list_id, type, content, position, created_at, updated_at FROM items WHERE list_id = $1 ORDER BY position ASC
`

func (q *Queries) GetItemsByList(ctx context.Context, listID pgtype.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItemsByList, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Type,
			&i.Content,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET content = $2, type = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, list_id, type, content, position, created_at, updated_at
`

type UpdateItemParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
	Type    ItemType    `json:"type"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem, arg.ID, arg.Content, arg.Type)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Type,
		&i.Content,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateItemPosition = `-- name: UpdateItemPosition :exec
UPDATE items SET position = $2, updated_at = NOW() WHERE id = $1
`

type UpdateItemPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	Position int32       `json:"position"`
}

func (q *Queries) UpdateItemPosition(ctx context.Context, arg UpdateItemPositionParams) error {
	_, err := q.db.Exec(ctx, updateItemPosition, arg.ID, arg.Position)
	return err
}
