// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToList = `-- name: AddTagToList :exec
INSERT INTO list_tags (list_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToListParams struct {
	ListID pgtype.UUID `json:"list_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToList(ctx context.Context, arg AddTagToListParams) error {
	_, err := q.db.Exec(ctx, addTagToList, arg.ListID, arg.TagID)
	return err
}

const getAllTags = `-- name: GetAllTags :many
SELECT id, name, created_at FROM tags ORDER BY name
`

func (q *Queries) GetAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListsByTag = `-- name: GetListsByTag :many
SELECT l.id, l.owner_id, l.title, l.description, l.is_public, l.created_at, l.updated_at FROM lists l
JOIN list_tags lt ON lt.list_id = l.id
WHERE lt.tag_id = $1
ORDER BY l.created_at DESC
`

func (q *Queries) GetListsByTag(ctx context.Context, tagID pgtype.UUID) ([]List, error) {
	rows, err := q.db.Query(ctx, getListsByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, created_at FROM tags WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at FROM tags WHERE name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagsByList = `-- name: GetTagsByList :many
SELECT t.id, t.name, t.created_at FROM tags t
JOIN list_tags lt ON lt.tag_id = t.id
WHERE lt.list_id = $1
ORDER BY t.name
`

func (q *Queries) GetTagsByList(ctx context.Context, listID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByList, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromList = `-- name: RemoveTagFromList :exec
DELETE FROM list_tags WHERE list_id = $1 AND tag_id = $2
`

type RemoveTagFromListParams struct {
	ListID pgtype.UUID `json:"list_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromList(ctx context.Context, arg RemoveTagFromListParams) error {
	_, err := q.db.Exec(ctx, removeTagFromList, arg.ListID, arg.TagID)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, created_at
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
