// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: birthdays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBirthday = `-- name: CreateBirthday :one
INSERT INTO birthdays (family_id, name, day, month, year, remind_days_before, created_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, family_id, name, day, month, year, remind_days_before, created_by_user_id, created_at, updated_at
`

type CreateBirthdayParams struct {
	FamilyID         pgtype.UUID
	Name             string
	Day              int32
	Month            int32
	Year             *int32
	RemindDaysBefore int32
	CreatedByUserID  pgtype.UUID
}

func (q *Queries) CreateBirthday(ctx context.Context, arg CreateBirthdayParams) (Birthday, error) {
	row := q.db.QueryRow(ctx, createBirthday,
		arg.FamilyID,
		arg.Name,
		arg.Day,
		arg.Month,
		arg.Year,
		arg.RemindDaysBefore,
		arg.CreatedByUserID,
	)
	var i Birthday
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Day,
		&i.Month,
		&i.Year,
		&i.RemindDaysBefore,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBirthday = `-- name: DeleteBirthday :execrows
DELETE FROM birthdays
WHERE id = $1 AND family_id = $2
`

type DeleteBirthdayParams struct {
	ID       pgtype.UUID
	FamilyID pgtype.UUID
}

func (q *Queries) DeleteBirthday(ctx context.Context, arg DeleteBirthdayParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBirthday, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBirthday = `-- name: GetBirthday :one
SELECT id, family_id, name, day, month, year, remind_days_before, created_by_user_id, created_at, updated_at FROM birthdays
WHERE id = $1 AND family_id = $2
`

type GetBirthdayParams struct {
	ID       pgtype.UUID
	FamilyID pgtype.UUID
}

func (q *Queries) GetBirthday(ctx context.Context, arg GetBirthdayParams) (Birthday, error) {
	row := q.db.QueryRow(ctx, getBirthday, arg.ID, arg.FamilyID)
	var i Birthday
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Day,
		&i.Month,
		&i.Year,
		&i.RemindDaysBefore,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllBirthdays = `-- name: ListAllBirthdays :many
SELECT id, family_id, name, day, month, year, remind_days_before, created_by_user_id, created_at, updated_at FROM birthdays
ORDER BY family_id, month, day, id
`

func (q *Queries) ListAllBirthdays(ctx context.Context) ([]Birthday, error) {
	rows, err := q.db.Query(ctx, listAllBirthdays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Birthday
	for rows.Next() {
		var i Birthday
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.RemindDaysBefore,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBirthdays = `-- name: ListBirthdays :many
SELECT id, family_id, name, day, month, year, remind_days_before, created_by_user_id, created_at, updated_at FROM birthdays
WHERE family_id = $1
ORDER BY month, day, name, id
`

func (q *Queries) ListBirthdays(ctx context.Context, familyID pgtype.UUID) ([]Birthday, error) {
	rows, err := q.db.Query(ctx, listBirthdays, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Birthday
	for rows.Next() {
		var i Birthday
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.Day,
			&i.Month,
			&i.Year,
			&i.RemindDaysBefore,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBirthday = `-- name: UpdateBirthday :one
UPDATE birthdays
SET name = $3, day = $4, month = $5, year = $6, remind_days_before = $7, updated_at = NOW()
WHERE id = $1 AND family_id = $2
RETURNING id, family_id, name, day, month, year, remind_days_before, created_by_user_id, created_at, updated_at
`

type UpdateBirthdayParams struct {
	ID               pgtype.UUID
	FamilyID         pgtype.UUID
	Name             string
	Day              int32
	Month            int32
	Year             *int32
	RemindDaysBefore int32
}

func (q *Queries) UpdateBirthday(ctx context.Context, arg UpdateBirthdayParams) (Birthday, error) {
	row := q.db.QueryRow(ctx, updateBirthday,
		arg.ID,
		arg.FamilyID,
		arg.Name,
		arg.Day,
		arg.Month,
		arg.Year,
		arg.RemindDaysBefore,
	)
	var i Birthday
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.Day,
		&i.Month,
		&i.Year,
		&i.RemindDaysBefore,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
