// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAssignee = `-- name: AddAssignee :exec
INSERT INTO task_assignees (task_id, family_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddAssigneeParams struct {
	TaskID   pgtype.UUID
	FamilyID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) AddAssignee(ctx context.Context, arg AddAssigneeParams) error {
	_, err := q.db.Exec(ctx, addAssignee, arg.TaskID, arg.FamilyID, arg.UserID)
	return err
}

const completeTask = `-- name: CompleteTask :one
UPDATE tasks
SET status = 'done', completed_at = $1, completed_by_user_id = $2, updated_at = NOW()
WHERE id = $3 AND family_id = $4 AND status = 'open'
RETURNING id, family_id, title, notes, priority, status, due_on, due_time, due_at, created_by_user_id, completed_by_user_id, completed_at, created_at, updated_at
`

type CompleteTaskParams struct {
	CompletedAt       pgtype.Timestamptz
	CompletedByUserID pgtype.UUID
	ID                pgtype.UUID
	FamilyID          pgtype.UUID
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, completeTask,
		arg.CompletedAt,
		arg.CompletedByUserID,
		arg.ID,
		arg.FamilyID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Status,
		&i.DueOn,
		&i.DueTime,
		&i.DueAt,
		&i.CreatedByUserID,
		&i.CompletedByUserID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (family_id, title, notes, priority, due_on, due_time, due_at, created_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, family_id, title, notes, priority, status, due_on, due_time, due_at, created_by_user_id, completed_by_user_id, completed_at, created_at, updated_at
`

type CreateTaskParams struct {
	FamilyID        pgtype.UUID
	Title           string
	Notes           string
	Priority        string
	DueOn           pgtype.Date
	DueTime         pgtype.Time
	DueAt           pgtype.Timestamptz
	CreatedByUserID pgtype.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.FamilyID,
		arg.Title,
		arg.Notes,
		arg.Priority,
		arg.DueOn,
		arg.DueTime,
		arg.DueAt,
		arg.CreatedByUserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Status,
		&i.DueOn,
		&i.DueTime,
		&i.DueAt,
		&i.CreatedByUserID,
		&i.CompletedByUserID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssignees = `-- name: DeleteAssignees :exec
DELETE FROM task_assignees
WHERE task_id = $1 AND family_id = $2
`

type DeleteAssigneesParams struct {
	TaskID   pgtype.UUID
	FamilyID pgtype.UUID
}

func (q *Queries) DeleteAssignees(ctx context.Context, arg DeleteAssigneesParams) error {
	_, err := q.db.Exec(ctx, deleteAssignees, arg.TaskID, arg.FamilyID)
	return err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks
WHERE id = $1 AND family_id = $2
`

type DeleteTaskParams struct {
	ID       pgtype.UUID
	FamilyID pgtype.UUID
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTask = `-- name: GetTask :one
SELECT id, family_id, title, notes, priority, status, due_on, due_time, due_at, created_by_user_id, completed_by_user_id, completed_at, created_at, updated_at FROM tasks
WHERE id = $1 AND family_id = $2
`

type GetTaskParams struct {
	ID       pgtype.UUID
	FamilyID pgtype.UUID
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.FamilyID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Status,
		&i.DueOn,
		&i.DueTime,
		&i.DueAt,
		&i.CreatedByUserID,
		&i.CompletedByUserID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT id, family_id, title, notes, priority, status, due_on, due_time, due_at, created_by_user_id, completed_by_user_id, completed_at, created_at, updated_at FROM tasks
WHERE id = $1 AND family_id = $2
FOR UPDATE
`

type GetTaskForUpdateParams struct {
	ID       pgtype.UUID
	FamilyID pgtype.UUID
}

func (q *Queries) GetTaskForUpdate(ctx context.Context, arg GetTaskForUpdateParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForUpdate, arg.ID, arg.FamilyID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Status,
		&i.DueOn,
		&i.DueTime,
		&i.DueAt,
		&i.CreatedByUserID,
		&i.CompletedByUserID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignees = `-- name: ListAssignees :many
SELECT task_id, user_id FROM task_assignees
WHERE family_id = $1 AND task_id = ANY($2::uuid[])
ORDER BY task_id, user_id
`

type ListAssigneesParams struct {
	FamilyID pgtype.UUID
	TaskIds  []pgtype.UUID
}

type ListAssigneesRow struct {
	TaskID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) ListAssignees(ctx context.Context, arg ListAssigneesParams) ([]ListAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listAssignees, arg.FamilyID, arg.TaskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssigneesRow
	for rows.Next() {
		var i ListAssigneesRow
		if err := rows.Scan(&i.TaskID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.family_id, t.title, t.notes, t.priority, t.status, t.due_on, t.due_time, t.due_at, t.created_by_user_id, t.completed_by_user_id, t.completed_at, t.created_at, t.updated_at FROM tasks t
WHERE t.family_id = $1
  AND ($2::text = '' OR t.status = $2::text)
  AND ($3::uuid IS NULL OR EXISTS (
        SELECT 1 FROM task_assignees a
        WHERE a.task_id = t.id AND a.family_id = t.family_id AND a.user_id = $3::uuid))
ORDER BY t.due_at NULLS LAST,
         CASE t.priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
         t.created_at, t.id
`

type ListTasksParams struct {
	FamilyID pgtype.UUID
	Status   string
	Assignee pgtype.UUID
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.FamilyID, arg.Status, arg.Assignee)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Title,
			&i.Notes,
			&i.Priority,
			&i.Status,
			&i.DueOn,
			&i.DueTime,
			&i.DueAt,
			&i.CreatedByUserID,
			&i.CompletedByUserID,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenTask = `-- name: ReopenTask :one
UPDATE tasks
SET status = 'open', completed_at = NULL, completed_by_user_id = NULL, updated_at = NOW()
WHERE id = $1 AND family_id = $2 AND status = 'done'
RETURNING id, family_id, title, notes, priority, status, due_on, due_time, due_at, created_by_user_id, completed_by_user_id, completed_at, created_at, updated_at
`

type ReopenTaskParams struct {
	ID       pgtype.UUID
	FamilyID pgtype.UUID
}

func (q *Queries) ReopenTask(ctx context.Context, arg ReopenTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, reopenTask, arg.ID, arg.FamilyID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Status,
		&i.DueOn,
		&i.DueTime,
		&i.DueAt,
		&i.CreatedByUserID,
		&i.CompletedByUserID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $3, notes = $4, priority = $5, due_on = $6, due_time = $7, due_at = $8, updated_at = NOW()
WHERE id = $1 AND family_id = $2
RETURNING id, family_id, title, notes, priority, status, due_on, due_time, due_at, created_by_user_id, completed_by_user_id, completed_at, created_at, updated_at
`

type UpdateTaskParams struct {
	ID       pgtype.UUID
	FamilyID pgtype.UUID
	Title    string
	Notes    string
	Priority string
	DueOn    pgtype.Date
	DueTime  pgtype.Time
	DueAt    pgtype.Timestamptz
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.FamilyID,
		arg.Title,
		arg.Notes,
		arg.Priority,
		arg.DueOn,
		arg.DueTime,
		arg.DueAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Status,
		&i.DueOn,
		&i.DueTime,
		&i.DueAt,
		&i.CreatedByUserID,
		&i.CompletedByUserID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
