// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: capture/v1/capture.proto

package capturev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nnc/family-manager/sdk/go/capture/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CaptureServiceName is the fully-qualified name of the CaptureService service.
	CaptureServiceName = "capture.v1.CaptureService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CaptureServiceSubmitNotificationsProcedure is the fully-qualified name of the CaptureService's
	// SubmitNotifications RPC.
	CaptureServiceSubmitNotificationsProcedure = "/capture.v1.CaptureService/SubmitNotifications"
	// CaptureServiceListSuggestionsProcedure is the fully-qualified name of the CaptureService's
	// ListSuggestions RPC.
	CaptureServiceListSuggestionsProcedure = "/capture.v1.CaptureService/ListSuggestions"
	// CaptureServiceConfirmSuggestionProcedure is the fully-qualified name of the CaptureService's
	// ConfirmSuggestion RPC.
	CaptureServiceConfirmSuggestionProcedure = "/capture.v1.CaptureService/ConfirmSuggestion"
	// CaptureServiceDismissSuggestionProcedure is the fully-qualified name of the CaptureService's
	// DismissSuggestion RPC.
	CaptureServiceDismissSuggestionProcedure = "/capture.v1.CaptureService/DismissSuggestion"
	// CaptureServiceListCapturedNotificationsProcedure is the fully-qualified name of the
	// CaptureService's ListCapturedNotifications RPC.
	CaptureServiceListCapturedNotificationsProcedure = "/capture.v1.CaptureService/ListCapturedNotifications"
	// CaptureServiceDeleteCapturedNotificationProcedure is the fully-qualified name of the
	// CaptureService's DeleteCapturedNotification RPC.
	CaptureServiceDeleteCapturedNotificationProcedure = "/capture.v1.CaptureService/DeleteCapturedNotification"
	// CaptureServiceGetCaptureSettingsProcedure is the fully-qualified name of the CaptureService's
	// GetCaptureSettings RPC.
	CaptureServiceGetCaptureSettingsProcedure = "/capture.v1.CaptureService/GetCaptureSettings"
	// CaptureServiceSetCaptureSettingsProcedure is the fully-qualified name of the CaptureService's
	// SetCaptureSettings RPC.
	CaptureServiceSetCaptureSettingsProcedure = "/capture.v1.CaptureService/SetCaptureSettings"
)

// CaptureServiceClient is a client for the capture.v1.CaptureService service.
type CaptureServiceClient interface {
	SubmitNotifications(context.Context, *connect.Request[v1.SubmitNotificationsRequest]) (*connect.Response[v1.SubmitNotificationsResponse], error)
	ListSuggestions(context.Context, *connect.Request[v1.ListSuggestionsRequest]) (*connect.Response[v1.ListSuggestionsResponse], error)
	ConfirmSuggestion(context.Context, *connect.Request[v1.ConfirmSuggestionRequest]) (*connect.Response[v1.ConfirmSuggestionResponse], error)
	DismissSuggestion(context.Context, *connect.Request[v1.DismissSuggestionRequest]) (*connect.Response[v1.DismissSuggestionResponse], error)
	ListCapturedNotifications(context.Context, *connect.Request[v1.ListCapturedNotificationsRequest]) (*connect.Response[v1.ListCapturedNotificationsResponse], error)
	DeleteCapturedNotification(context.Context, *connect.Request[v1.DeleteCapturedNotificationRequest]) (*connect.Response[v1.DeleteCapturedNotificationResponse], error)
	GetCaptureSettings(context.Context, *connect.Request[v1.GetCaptureSettingsRequest]) (*connect.Response[v1.GetCaptureSettingsResponse], error)
	SetCaptureSettings(context.Context, *connect.Request[v1.SetCaptureSettingsRequest]) (*connect.Response[v1.SetCaptureSettingsResponse], error)
}

// NewCaptureServiceClient constructs a client for the capture.v1.CaptureService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCaptureServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CaptureServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	captureServiceMethods := v1.File_capture_v1_capture_proto.Services().ByName("CaptureService").Methods()
	return &captureServiceClient{
		submitNotifications: connect.NewClient[v1.SubmitNotificationsRequest, v1.SubmitNotificationsResponse](
			httpClient,
			baseURL+CaptureServiceSubmitNotificationsProcedure,
			connect.WithSchema(captureServiceMethods.ByName("SubmitNotifications")),
			connect.WithClientOptions(opts...),
		),
		listSuggestions: connect.NewClient[v1.ListSuggestionsRequest, v1.ListSuggestionsResponse](
			httpClient,
			baseURL+CaptureServiceListSuggestionsProcedure,
			connect.WithSchema(captureServiceMethods.ByName("ListSuggestions")),
			connect.WithClientOptions(opts...),
		),
		confirmSuggestion: connect.NewClient[v1.ConfirmSuggestionRequest, v1.ConfirmSuggestionResponse](
			httpClient,
			baseURL+CaptureServiceConfirmSuggestionProcedure,
			connect.WithSchema(captureServiceMethods.ByName("ConfirmSuggestion")),
			connect.WithClientOptions(opts...),
		),
		dismissSuggestion: connect.NewClient[v1.DismissSuggestionRequest, v1.DismissSuggestionResponse](
			httpClient,
			baseURL+CaptureServiceDismissSuggestionProcedure,
			connect.WithSchema(captureServiceMethods.ByName("DismissSuggestion")),
			connect.WithClientOptions(opts...),
		),
		listCapturedNotifications: connect.NewClient[v1.ListCapturedNotificationsRequest, v1.ListCapturedNotificationsResponse](
			httpClient,
			baseURL+CaptureServiceListCapturedNotificationsProcedure,
			connect.WithSchema(captureServiceMethods.ByName("ListCapturedNotifications")),
			connect.WithClientOptions(opts...),
		),
		deleteCapturedNotification: connect.NewClient[v1.DeleteCapturedNotificationRequest, v1.DeleteCapturedNotificationResponse](
			httpClient,
			baseURL+CaptureServiceDeleteCapturedNotificationProcedure,
			connect.WithSchema(captureServiceMethods.ByName("DeleteCapturedNotification")),
			connect.WithClientOptions(opts...),
		),
		getCaptureSettings: connect.NewClient[v1.GetCaptureSettingsRequest, v1.GetCaptureSettingsResponse](
			httpClient,
			baseURL+CaptureServiceGetCaptureSettingsProcedure,
			connect.WithSchema(captureServiceMethods.ByName("GetCaptureSettings")),
			connect.WithClientOptions(opts...),
		),
		setCaptureSettings: connect.NewClient[v1.SetCaptureSettingsRequest, v1.SetCaptureSettingsResponse](
			httpClient,
			baseURL+CaptureServiceSetCaptureSettingsProcedure,
			connect.WithSchema(captureServiceMethods.ByName("SetCaptureSettings")),
			connect.WithClientOptions(opts...),
		),
	}
}

// captureServiceClient implements CaptureServiceClient.
type captureServiceClient struct {
	submitNotifications        *connect.Client[v1.SubmitNotificationsRequest, v1.SubmitNotificationsResponse]
	listSuggestions            *connect.Client[v1.ListSuggestionsRequest, v1.ListSuggestionsResponse]
	confirmSuggestion          *connect.Client[v1.ConfirmSuggestionRequest, v1.ConfirmSuggestionResponse]
	dismissSuggestion          *connect.Client[v1.DismissSuggestionRequest, v1.DismissSuggestionResponse]
	listCapturedNotifications  *connect.Client[v1.ListCapturedNotificationsRequest, v1.ListCapturedNotificationsResponse]
	deleteCapturedNotification *connect.Client[v1.DeleteCapturedNotificationRequest, v1.DeleteCapturedNotificationResponse]
	getCaptureSettings         *connect.Client[v1.GetCaptureSettingsRequest, v1.GetCaptureSettingsResponse]
	setCaptureSettings         *connect.Client[v1.SetCaptureSettingsRequest, v1.SetCaptureSettingsResponse]
}

// SubmitNotifications calls capture.v1.CaptureService.SubmitNotifications.
func (c *captureServiceClient) SubmitNotifications(ctx context.Context, req *connect.Request[v1.SubmitNotificationsRequest]) (*connect.Response[v1.SubmitNotificationsResponse], error) {
	return c.submitNotifications.CallUnary(ctx, req)
}

// ListSuggestions calls capture.v1.CaptureService.ListSuggestions.
func (c *captureServiceClient) ListSuggestions(ctx context.Context, req *connect.Request[v1.ListSuggestionsRequest]) (*connect.Response[v1.ListSuggestionsResponse], error) {
	return c.listSuggestions.CallUnary(ctx, req)
}

// ConfirmSuggestion calls capture.v1.CaptureService.ConfirmSuggestion.
func (c *captureServiceClient) ConfirmSuggestion(ctx context.Context, req *connect.Request[v1.ConfirmSuggestionRequest]) (*connect.Response[v1.ConfirmSuggestionResponse], error) {
	return c.confirmSuggestion.CallUnary(ctx, req)
}

// DismissSuggestion calls capture.v1.CaptureService.DismissSuggestion.
func (c *captureServiceClient) DismissSuggestion(ctx context.Context, req *connect.Request[v1.DismissSuggestionRequest]) (*connect.Response[v1.DismissSuggestionResponse], error) {
	return c.dismissSuggestion.CallUnary(ctx, req)
}

// ListCapturedNotifications calls capture.v1.CaptureService.ListCapturedNotifications.
func (c *captureServiceClient) ListCapturedNotifications(ctx context.Context, req *connect.Request[v1.ListCapturedNotificationsRequest]) (*connect.Response[v1.ListCapturedNotificationsResponse], error) {
	return c.listCapturedNotifications.CallUnary(ctx, req)
}

// DeleteCapturedNotification calls capture.v1.CaptureService.DeleteCapturedNotification.
func (c *captureServiceClient) DeleteCapturedNotification(ctx context.Context, req *connect.Request[v1.DeleteCapturedNotificationRequest]) (*connect.Response[v1.DeleteCapturedNotificationResponse], error) {
	return c.deleteCapturedNotification.CallUnary(ctx, req)
}

// GetCaptureSettings calls capture.v1.CaptureService.GetCaptureSettings.
func (c *captureServiceClient) GetCaptureSettings(ctx context.Context, req *connect.Request[v1.GetCaptureSettingsRequest]) (*connect.Response[v1.GetCaptureSettingsResponse], error) {
	return c.getCaptureSettings.CallUnary(ctx, req)
}

// SetCaptureSettings calls capture.v1.CaptureService.SetCaptureSettings.
func (c *captureServiceClient) SetCaptureSettings(ctx context.Context, req *connect.Request[v1.SetCaptureSettingsRequest]) (*connect.Response[v1.SetCaptureSettingsResponse], error) {
	return c.setCaptureSettings.CallUnary(ctx, req)
}

// CaptureServiceHandler is an implementation of the capture.v1.CaptureService service.
type CaptureServiceHandler interface {
	SubmitNotifications(context.Context, *connect.Request[v1.SubmitNotificationsRequest]) (*connect.Response[v1.SubmitNotificationsResponse], error)
	ListSuggestions(context.Context, *connect.Request[v1.ListSuggestionsRequest]) (*connect.Response[v1.ListSuggestionsResponse], error)
	ConfirmSuggestion(context.Context, *connect.Request[v1.ConfirmSuggestionRequest]) (*connect.Response[v1.ConfirmSuggestionResponse], error)
	DismissSuggestion(context.Context, *connect.Request[v1.DismissSuggestionRequest]) (*connect.Response[v1.DismissSuggestionResponse], error)
	ListCapturedNotifications(context.Context, *connect.Request[v1.ListCapturedNotificationsRequest]) (*connect.Response[v1.ListCapturedNotificationsResponse], error)
	DeleteCapturedNotification(context.Context, *connect.Request[v1.DeleteCapturedNotificationRequest]) (*connect.Response[v1.DeleteCapturedNotificationResponse], error)
	GetCaptureSettings(context.Context, *connect.Request[v1.GetCaptureSettingsRequest]) (*connect.Response[v1.GetCaptureSettingsResponse], error)
	SetCaptureSettings(context.Context, *connect.Request[v1.SetCaptureSettingsRequest]) (*connect.Response[v1.SetCaptureSettingsResponse], error)
}

// NewCaptureServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCaptureServiceHandler(svc CaptureServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	captureServiceMethods := v1.File_capture_v1_capture_proto.Services().ByName("CaptureService").Methods()
	captureServiceSubmitNotificationsHandler := connect.NewUnaryHandler(
		CaptureServiceSubmitNotificationsProcedure,
		svc.SubmitNotifications,
		connect.WithSchema(captureServiceMethods.ByName("SubmitNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	captureServiceListSuggestionsHandler := connect.NewUnaryHandler(
		CaptureServiceListSuggestionsProcedure,
		svc.ListSuggestions,
		connect.WithSchema(captureServiceMethods.ByName("ListSuggestions")),
		connect.WithHandlerOptions(opts...),
	)
	captureServiceConfirmSuggestionHandler := connect.NewUnaryHandler(
		CaptureServiceConfirmSuggestionProcedure,
		svc.ConfirmSuggestion,
		connect.WithSchema(captureServiceMethods.ByName("ConfirmSuggestion")),
		connect.WithHandlerOptions(opts...),
	)
	captureServiceDismissSuggestionHandler := connect.NewUnaryHandler(
		CaptureServiceDismissSuggestionProcedure,
		svc.DismissSuggestion,
		connect.WithSchema(captureServiceMethods.ByName("DismissSuggestion")),
		connect.WithHandlerOptions(opts...),
	)
	captureServiceListCapturedNotificationsHandler := connect.NewUnaryHandler(
		CaptureServiceListCapturedNotificationsProcedure,
		svc.ListCapturedNotifications,
		connect.WithSchema(captureServiceMethods.ByName("ListCapturedNotifications")),
		connect.WithHandlerOptions(opts...),
	)
	captureServiceDeleteCapturedNotificationHandler := connect.NewUnaryHandler(
		CaptureServiceDeleteCapturedNotificationProcedure,
		svc.DeleteCapturedNotification,
		connect.WithSchema(captureServiceMethods.ByName("DeleteCapturedNotification")),
		connect.WithHandlerOptions(opts...),
	)
	captureServiceGetCaptureSettingsHandler := connect.NewUnaryHandler(
		CaptureServiceGetCaptureSettingsProcedure,
		svc.GetCaptureSettings,
		connect.WithSchema(captureServiceMethods.ByName("GetCaptureSettings")),
		connect.WithHandlerOptions(opts...),
	)
	captureServiceSetCaptureSettingsHandler := connect.NewUnaryHandler(
		CaptureServiceSetCaptureSettingsProcedure,
		svc.SetCaptureSettings,
		connect.WithSchema(captureServiceMethods.ByName("SetCaptureSettings")),
		connect.WithHandlerOptions(opts...),
	)
	return "/capture.v1.CaptureService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CaptureServiceSubmitNotificationsProcedure:
			captureServiceSubmitNotificationsHandler.ServeHTTP(w, r)
		case CaptureServiceListSuggestionsProcedure:
			captureServiceListSuggestionsHandler.ServeHTTP(w, r)
		case CaptureServiceConfirmSuggestionProcedure:
			captureServiceConfirmSuggestionHandler.ServeHTTP(w, r)
		case CaptureServiceDismissSuggestionProcedure:
			captureServiceDismissSuggestionHandler.ServeHTTP(w, r)
		case CaptureServiceListCapturedNotificationsProcedure:
			captureServiceListCapturedNotificationsHandler.ServeHTTP(w, r)
		case CaptureServiceDeleteCapturedNotificationProcedure:
			captureServiceDeleteCapturedNotificationHandler.ServeHTTP(w, r)
		case CaptureServiceGetCaptureSettingsProcedure:
			captureServiceGetCaptureSettingsHandler.ServeHTTP(w, r)
		case CaptureServiceSetCaptureSettingsProcedure:
			captureServiceSetCaptureSettingsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCaptureServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCaptureServiceHandler struct{}

func (UnimplementedCaptureServiceHandler) SubmitNotifications(context.Context, *connect.Request[v1.SubmitNotificationsRequest]) (*connect.Response[v1.SubmitNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("capture.v1.CaptureService.SubmitNotifications is not implemented"))
}

func (UnimplementedCaptureServiceHandler) ListSuggestions(context.Context, *connect.Request[v1.ListSuggestionsRequest]) (*connect.Response[v1.ListSuggestionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("capture.v1.CaptureService.ListSuggestions is not implemented"))
}

func (UnimplementedCaptureServiceHandler) ConfirmSuggestion(context.Context, *connect.Request[v1.ConfirmSuggestionRequest]) (*connect.Response[v1.ConfirmSuggestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("capture.v1.CaptureService.ConfirmSuggestion is not implemented"))
}

func (UnimplementedCaptureServiceHandler) DismissSuggestion(context.Context, *connect.Request[v1.DismissSuggestionRequest]) (*connect.Response[v1.DismissSuggestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("capture.v1.CaptureService.DismissSuggestion is not implemented"))
}

func (UnimplementedCaptureServiceHandler) ListCapturedNotifications(context.Context, *connect.Request[v1.ListCapturedNotificationsRequest]) (*connect.Response[v1.ListCapturedNotificationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("capture.v1.CaptureService.ListCapturedNotifications is not implemented"))
}

func (UnimplementedCaptureServiceHandler) DeleteCapturedNotification(context.Context, *connect.Request[v1.DeleteCapturedNotificationRequest]) (*connect.Response[v1.DeleteCapturedNotificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("capture.v1.CaptureService.DeleteCapturedNotification is not implemented"))
}

func (UnimplementedCaptureServiceHandler) GetCaptureSettings(context.Context, *connect.Request[v1.GetCaptureSettingsRequest]) (*connect.Response[v1.GetCaptureSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("capture.v1.CaptureService.GetCaptureSettings is not implemented"))
}

func (UnimplementedCaptureServiceHandler) SetCaptureSettings(context.Context, *connect.Request[v1.SetCaptureSettingsRequest]) (*connect.Response[v1.SetCaptureSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("capture.v1.CaptureService.SetCaptureSettings is not implemented"))
}
