// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceInstallment = `-- name: AdvanceInstallment :one
UPDATE installments
SET next_due_on = $2::date,
    status      = $3::text,
    updated_at  = NOW()
WHERE id = $1 AND next_due_on = $4::date AND status = 'active'
RETURNING id, family_id, name, total_minor, monthly_minor, months, currency_code, account_id, category_id, member_id, created_by_user_id, purchased_on, day_of_month, next_due_on, status, created_at, updated_at
`

type AdvanceInstallmentParams struct {
	ID            pgtype.UUID
	NextDueOn     pgtype.Date
	Status        string
	ExpectedDueOn pgtype.Date
}

func (q *Queries) AdvanceInstallment(ctx context.Context, arg AdvanceInstallmentParams) (Installment, error) {
	row := q.db.QueryRow(ctx, advanceInstallment,
		arg.ID,
		arg.NextDueOn,
		arg.Status,
		arg.ExpectedDueOn,
	)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.TotalMinor,
		&i.MonthlyMinor,
		&i.Months,
		&i.CurrencyCode,
		&i.AccountID,
		&i.CategoryID,
		&i.MemberID,
		&i.CreatedByUserID,
		&i.PurchasedOn,
		&i.DayOfMonth,
		&i.NextDueOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstallment = `-- name: CreateInstallment :one
INSERT INTO installments (family_id, name, total_minor, monthly_minor, months, currency_code,
    account_id, category_id, member_id, created_by_user_id, purchased_on, day_of_month, next_due_on)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, family_id, name, total_minor, monthly_minor, months, currency_code, account_id, category_id, member_id, created_by_user_id, purchased_on, day_of_month, next_due_on, status, created_at, updated_at
`

type CreateInstallmentParams struct {
	FamilyID        pgtype.UUID
	Name            string
	TotalMinor      int64
	MonthlyMinor    int64
	Months          int32
	CurrencyCode    string
	AccountID       pgtype.UUID
	CategoryID      pgtype.UUID
	MemberID        pgtype.UUID
	CreatedByUserID pgtype.UUID
	PurchasedOn     pgtype.Date
	DayOfMonth      int32
	NextDueOn       pgtype.Date
}

func (q *Queries) CreateInstallment(ctx context.Context, arg CreateInstallmentParams) (Installment, error) {
	row := q.db.QueryRow(ctx, createInstallment,
		arg.FamilyID,
		arg.Name,
		arg.TotalMinor,
		arg.MonthlyMinor,
		arg.Months,
		arg.CurrencyCode,
		arg.AccountID,
		arg.CategoryID,
		arg.MemberID,
		arg.CreatedByUserID,
		arg.PurchasedOn,
		arg.DayOfMonth,
		arg.NextDueOn,
	)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.TotalMinor,
		&i.MonthlyMinor,
		&i.Months,
		&i.CurrencyCode,
		&i.AccountID,
		&i.CategoryID,
		&i.MemberID,
		&i.CreatedByUserID,
		&i.PurchasedOn,
		&i.DayOfMonth,
		&i.NextDueOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInstallment = `-- name: DeleteInstallment :execrows
DELETE FROM installments
WHERE id = $1 AND family_id = $2
`

type DeleteInstallmentParams struct {
	ID       pgtype.UUID
	FamilyID pgtype.UUID
}

func (q *Queries) DeleteInstallment(ctx context.Context, arg DeleteInstallmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInstallment, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInstallmentByID = `-- name: GetInstallmentByID :one
SELECT id, family_id, name, total_minor, monthly_minor, months, currency_code, account_id, category_id, member_id, created_by_user_id, purchased_on, day_of_month, next_due_on, status, created_at, updated_at FROM installments
WHERE id = $1
`

func (q *Queries) GetInstallmentByID(ctx context.Context, id pgtype.UUID) (Installment, error) {
	row := q.db.QueryRow(ctx, getInstallmentByID, id)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.TotalMinor,
		&i.MonthlyMinor,
		&i.Months,
		&i.CurrencyCode,
		&i.AccountID,
		&i.CategoryID,
		&i.MemberID,
		&i.CreatedByUserID,
		&i.PurchasedOn,
		&i.DayOfMonth,
		&i.NextDueOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVisibleInstallment = `-- name: GetVisibleInstallment :one
SELECT i.id, i.family_id, i.name, i.total_minor, i.monthly_minor, i.months, i.currency_code, i.account_id, i.category_id, i.member_id, i.created_by_user_id, i.purchased_on, i.day_of_month, i.next_due_on, i.status, i.created_at, i.updated_at
FROM installments i
JOIN accounts a ON a.id = i.account_id
WHERE i.id = $1
  AND i.family_id = $2
  AND (a.visibility = 'shared' OR a.owner_member_id = $3::uuid)
`

type GetVisibleInstallmentParams struct {
	ID             pgtype.UUID
	FamilyID       pgtype.UUID
	ViewerMemberID pgtype.UUID
}

func (q *Queries) GetVisibleInstallment(ctx context.Context, arg GetVisibleInstallmentParams) (Installment, error) {
	row := q.db.QueryRow(ctx, getVisibleInstallment, arg.ID, arg.FamilyID, arg.ViewerMemberID)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.TotalMinor,
		&i.MonthlyMinor,
		&i.Months,
		&i.CurrencyCode,
		&i.AccountID,
		&i.CategoryID,
		&i.MemberID,
		&i.CreatedByUserID,
		&i.PurchasedOn,
		&i.DayOfMonth,
		&i.NextDueOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueInstallments = `-- name: ListDueInstallments :many
SELECT id, family_id, category_id, next_due_on
FROM installments
WHERE status = 'active'
  AND next_due_on <= $1::date
ORDER BY next_due_on
LIMIT $2::int
`

type ListDueInstallmentsParams struct {
	LatestDueOn pgtype.Date
	MaxRows     int32
}

type ListDueInstallmentsRow struct {
	ID         pgtype.UUID
	FamilyID   pgtype.UUID
	CategoryID pgtype.UUID
	NextDueOn  pgtype.Date
}

func (q *Queries) ListDueInstallments(ctx context.Context, arg ListDueInstallmentsParams) ([]ListDueInstallmentsRow, error) {
	rows, err := q.db.Query(ctx, listDueInstallments, arg.LatestDueOn, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueInstallmentsRow
	for rows.Next() {
		var i ListDueInstallmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.CategoryID,
			&i.NextDueOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleInstallments = `-- name: ListVisibleInstallments :many
SELECT i.id, i.family_id, i.name, i.total_minor, i.monthly_minor, i.months, i.currency_code, i.account_id, i.category_id, i.member_id, i.created_by_user_id, i.purchased_on, i.day_of_month, i.next_due_on, i.status, i.created_at, i.updated_at, c.group_id AS group_id,
    COALESCE(p.paid_minor, 0)::bigint AS paid_minor,
    COALESCE(p.payments, 0)::bigint AS payments
FROM installments i
JOIN accounts a ON a.id = i.account_id
JOIN categories c ON c.id = i.category_id
LEFT JOIN LATERAL (
    SELECT SUM(t.amount_minor) AS paid_minor, COUNT(*) AS payments
    FROM transactions t
    WHERE t.family_id = i.family_id
      AND t.category_id = i.category_id
      AND t.type = 'expense'
      AND t.currency_code = i.currency_code
) p ON TRUE
WHERE i.family_id = $1
  AND (a.visibility = 'shared' OR a.owner_member_id = $2::uuid)
  AND ($3::bool OR i.status = 'active')
ORDER BY i.status = 'active' DESC, i.next_due_on, i.created_at
`

type ListVisibleInstallmentsParams struct {
	FamilyID       pgtype.UUID
	ViewerMemberID pgtype.UUID
	IncludeClosed  bool
}

type ListVisibleInstallmentsRow struct {
	Installment Installment
	GroupID     pgtype.UUID
	PaidMinor   int64
	Payments    int64
}

func (q *Queries) ListVisibleInstallments(ctx context.Context, arg ListVisibleInstallmentsParams) ([]ListVisibleInstallmentsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleInstallments, arg.FamilyID, arg.ViewerMemberID, arg.IncludeClosed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVisibleInstallmentsRow
	for rows.Next() {
		var i ListVisibleInstallmentsRow
		if err := rows.Scan(
			&i.Installment.ID,
			&i.Installment.FamilyID,
			&i.Installment.Name,
			&i.Installment.TotalMinor,
			&i.Installment.MonthlyMinor,
			&i.Installment.Months,
			&i.Installment.CurrencyCode,
			&i.Installment.AccountID,
			&i.Installment.CategoryID,
			&i.Installment.MemberID,
			&i.Installment.CreatedByUserID,
			&i.Installment.PurchasedOn,
			&i.Installment.DayOfMonth,
			&i.Installment.NextDueOn,
			&i.Installment.Status,
			&i.Installment.CreatedAt,
			&i.Installment.UpdatedAt,
			&i.GroupID,
			&i.PaidMinor,
			&i.Payments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDueInstallment = `-- name: LockDueInstallment :one
SELECT id, family_id, name, total_minor, monthly_minor, months, currency_code, account_id, category_id, member_id, created_by_user_id, purchased_on, day_of_month, next_due_on, status, created_at, updated_at FROM installments
WHERE id = $1 AND status = 'active'
FOR UPDATE SKIP LOCKED
`

func (q *Queries) LockDueInstallment(ctx context.Context, id pgtype.UUID) (Installment, error) {
	row := q.db.QueryRow(ctx, lockDueInstallment, id)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.TotalMinor,
		&i.MonthlyMinor,
		&i.Months,
		&i.CurrencyCode,
		&i.AccountID,
		&i.CategoryID,
		&i.MemberID,
		&i.CreatedByUserID,
		&i.PurchasedOn,
		&i.DayOfMonth,
		&i.NextDueOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumInstallmentPayments = `-- name: SumInstallmentPayments :one
SELECT COALESCE(SUM(amount_minor), 0)::bigint AS paid_minor, COUNT(*)::bigint AS payments
FROM transactions
WHERE family_id = $1 AND category_id = $2 AND type = 'expense' AND currency_code = $3
`

type SumInstallmentPaymentsParams struct {
	FamilyID     pgtype.UUID
	CategoryID   pgtype.UUID
	CurrencyCode string
}

type SumInstallmentPaymentsRow struct {
	PaidMinor int64
	Payments  int64
}

func (q *Queries) SumInstallmentPayments(ctx context.Context, arg SumInstallmentPaymentsParams) (SumInstallmentPaymentsRow, error) {
	row := q.db.QueryRow(ctx, sumInstallmentPayments, arg.FamilyID, arg.CategoryID, arg.CurrencyCode)
	var i SumInstallmentPaymentsRow
	err := row.Scan(&i.PaidMinor, &i.Payments)
	return i, err
}

const updateInstallment = `-- name: UpdateInstallment :one
UPDATE installments
SET name          = COALESCE($3::text, name),
    monthly_minor = COALESCE($4::bigint, monthly_minor),
    account_id    = COALESCE($5::uuid, account_id),
    member_id     = COALESCE($6::uuid, member_id),
    day_of_month  = COALESCE($7::int, day_of_month),
    next_due_on   = COALESCE($8::date, next_due_on),
    status        = COALESCE($9::text, status),
    updated_at    = NOW()
WHERE id = $1 AND family_id = $2
RETURNING id, family_id, name, total_minor, monthly_minor, months, currency_code, account_id, category_id, member_id, created_by_user_id, purchased_on, day_of_month, next_due_on, status, created_at, updated_at
`

type UpdateInstallmentParams struct {
	ID           pgtype.UUID
	FamilyID     pgtype.UUID
	Name         *string
	MonthlyMinor *int64
	AccountID    pgtype.UUID
	MemberID     pgtype.UUID
	DayOfMonth   *int32
	NextDueOn    pgtype.Date
	Status       *string
}

func (q *Queries) UpdateInstallment(ctx context.Context, arg UpdateInstallmentParams) (Installment, error) {
	row := q.db.QueryRow(ctx, updateInstallment,
		arg.ID,
		arg.FamilyID,
		arg.Name,
		arg.MonthlyMinor,
		arg.AccountID,
		arg.MemberID,
		arg.DayOfMonth,
		arg.NextDueOn,
		arg.Status,
	)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.TotalMinor,
		&i.MonthlyMinor,
		&i.Months,
		&i.CurrencyCode,
		&i.AccountID,
		&i.CategoryID,
		&i.MemberID,
		&i.CreatedByUserID,
		&i.PurchasedOn,
		&i.DayOfMonth,
		&i.NextDueOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
