// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceRecurringPayment = `-- name: AdvanceRecurringPayment :one
UPDATE recurring_payments
SET next_due_on = $3, last_posted_on = $4::date, updated_at = NOW()
WHERE id = $1 AND family_id = $2
RETURNING id, family_id, name, amount_minor, currency_code, type, category_id, account_id, member_id, interval_count, interval_unit, day_of_month, day_of_week, next_due_on, end_on, auto_post, active, last_posted_on, created_at, updated_at
`

type AdvanceRecurringPaymentParams struct {
	ID           pgtype.UUID
	FamilyID     pgtype.UUID
	NextDueOn    pgtype.Date
	LastPostedOn pgtype.Date
}

func (q *Queries) AdvanceRecurringPayment(ctx context.Context, arg AdvanceRecurringPaymentParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, advanceRecurringPayment,
		arg.ID,
		arg.FamilyID,
		arg.NextDueOn,
		arg.LastPostedOn,
	)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.AmountMinor,
		&i.CurrencyCode,
		&i.Type,
		&i.CategoryID,
		&i.AccountID,
		&i.MemberID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.NextDueOn,
		&i.EndOn,
		&i.AutoPost,
		&i.Active,
		&i.LastPostedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecurringPayment = `-- name: CreateRecurringPayment :one
INSERT INTO recurring_payments (family_id, name, amount_minor, currency_code, type,
    category_id, account_id, member_id, interval_count, interval_unit, day_of_month,
    day_of_week, next_due_on, end_on, auto_post)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, family_id, name, amount_minor, currency_code, type, category_id, account_id, member_id, interval_count, interval_unit, day_of_month, day_of_week, next_due_on, end_on, auto_post, active, last_posted_on, created_at, updated_at
`

type CreateRecurringPaymentParams struct {
	FamilyID      pgtype.UUID
	Name          string
	AmountMinor   int64
	CurrencyCode  string
	Type          string
	CategoryID    pgtype.UUID
	AccountID     pgtype.UUID
	MemberID      pgtype.UUID
	IntervalCount int32
	IntervalUnit  string
	DayOfMonth    int32
	DayOfWeek     string
	NextDueOn     pgtype.Date
	EndOn         pgtype.Date
	AutoPost      bool
}

func (q *Queries) CreateRecurringPayment(ctx context.Context, arg CreateRecurringPaymentParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, createRecurringPayment,
		arg.FamilyID,
		arg.Name,
		arg.AmountMinor,
		arg.CurrencyCode,
		arg.Type,
		arg.CategoryID,
		arg.AccountID,
		arg.MemberID,
		arg.IntervalCount,
		arg.IntervalUnit,
		arg.DayOfMonth,
		arg.DayOfWeek,
		arg.NextDueOn,
		arg.EndOn,
		arg.AutoPost,
	)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.AmountMinor,
		&i.CurrencyCode,
		&i.Type,
		&i.CategoryID,
		&i.AccountID,
		&i.MemberID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.NextDueOn,
		&i.EndOn,
		&i.AutoPost,
		&i.Active,
		&i.LastPostedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecurringPayment = `-- name: DeleteRecurringPayment :execrows
DELETE FROM recurring_payments
WHERE id = $1 AND family_id = $2
`

type DeleteRecurringPaymentParams struct {
	ID       pgtype.UUID
	FamilyID pgtype.UUID
}

func (q *Queries) DeleteRecurringPayment(ctx context.Context, arg DeleteRecurringPaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecurringPayment, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVisibleRecurringPayment = `-- name: GetVisibleRecurringPayment :one
SELECT r.id, r.family_id, r.name, r.amount_minor, r.currency_code, r.type, r.category_id, r.account_id, r.member_id, r.interval_count, r.interval_unit, r.day_of_month, r.day_of_week, r.next_due_on, r.end_on, r.auto_post, r.active, r.last_posted_on, r.created_at, r.updated_at
FROM recurring_payments r
JOIN accounts a ON a.id = r.account_id
WHERE r.id = $1
  AND r.family_id = $2
  AND (a.visibility = 'shared' OR a.owner_member_id = $3::uuid)
`

type GetVisibleRecurringPaymentParams struct {
	ID             pgtype.UUID
	FamilyID       pgtype.UUID
	ViewerMemberID pgtype.UUID
}

// GetVisibleRecurringPayment answers NotFound for a schedule on another member's private
// account, the same answer as an id that never existed: "this id exists but is not yours" is
// itself a leak, and a write RPC that skipped this read would be a read of exactly what the
// boundary hides.
func (q *Queries) GetVisibleRecurringPayment(ctx context.Context, arg GetVisibleRecurringPaymentParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, getVisibleRecurringPayment, arg.ID, arg.FamilyID, arg.ViewerMemberID)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.AmountMinor,
		&i.CurrencyCode,
		&i.Type,
		&i.CategoryID,
		&i.AccountID,
		&i.MemberID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.NextDueOn,
		&i.EndOn,
		&i.AutoPost,
		&i.Active,
		&i.LastPostedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVisibleRecurringPayments = `-- name: ListVisibleRecurringPayments :many

SELECT r.id, r.family_id, r.name, r.amount_minor, r.currency_code, r.type, r.category_id, r.account_id, r.member_id, r.interval_count, r.interval_unit, r.day_of_month, r.day_of_week, r.next_due_on, r.end_on, r.auto_post, r.active, r.last_posted_on, r.created_at, r.updated_at
FROM recurring_payments r
JOIN accounts a ON a.id = r.account_id
WHERE r.family_id = $1
  AND (a.visibility = 'shared' OR a.owner_member_id = $2::uuid)
  AND ($3::bool OR r.active)
ORDER BY r.next_due_on, r.created_at
`

type ListVisibleRecurringPaymentsParams struct {
	FamilyID        pgtype.UUID
	ViewerMemberID  pgtype.UUID
	IncludeInactive bool
}

// A recurring payment is attached to an account, so it inherits that account's visibility:
// the schedule's name, amount and cadence say as much about a private account as a
// transaction does. Every read therefore joins accounts and carries the same predicate the
// rest of this directory carries
//
//	(a.visibility = 'shared' OR a.owner_member_id = @viewer_member_id)
//
// and is named Visible* so a handler reaching for an unscoped read has to notice there isn't
// one. Writes are gated by reading the row through GetVisibleRecurringPayment first — the
// same "the read is the guard" rule accounts.sql states.
func (q *Queries) ListVisibleRecurringPayments(ctx context.Context, arg ListVisibleRecurringPaymentsParams) ([]RecurringPayment, error) {
	rows, err := q.db.Query(ctx, listVisibleRecurringPayments, arg.FamilyID, arg.ViewerMemberID, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringPayment
	for rows.Next() {
		var i RecurringPayment
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Name,
			&i.AmountMinor,
			&i.CurrencyCode,
			&i.Type,
			&i.CategoryID,
			&i.AccountID,
			&i.MemberID,
			&i.IntervalCount,
			&i.IntervalUnit,
			&i.DayOfMonth,
			&i.DayOfWeek,
			&i.NextDueOn,
			&i.EndOn,
			&i.AutoPost,
			&i.Active,
			&i.LastPostedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringPayment = `-- name: UpdateRecurringPayment :one
UPDATE recurring_payments
SET name           = COALESCE($3::text, name),
    amount_minor   = COALESCE($4::bigint, amount_minor),
    -- Same rule as quick_templates: the schedule is denominated in its account's currency, so
    -- moving it to another account moves the currency with it.
    currency_code  = COALESCE($5::text, currency_code),
    category_id    = COALESCE($6::uuid, category_id),
    account_id     = COALESCE($7::uuid, account_id),
    member_id      = COALESCE($8::uuid, member_id),
    interval_count = COALESCE($9::int, interval_count),
    interval_unit  = COALESCE($10::text, interval_unit),
    day_of_month   = COALESCE($11::int, day_of_month),
    day_of_week    = COALESCE($12::text, day_of_week),
    next_due_on    = COALESCE($13::date, next_due_on),
    end_on         = COALESCE($14::date, end_on),
    auto_post      = COALESCE($15::bool, auto_post),
    active         = COALESCE($16::bool, active),
    updated_at     = NOW()
WHERE id = $1 AND family_id = $2
RETURNING id, family_id, name, amount_minor, currency_code, type, category_id, account_id, member_id, interval_count, interval_unit, day_of_month, day_of_week, next_due_on, end_on, auto_post, active, last_posted_on, created_at, updated_at
`

type UpdateRecurringPaymentParams struct {
	ID            pgtype.UUID
	FamilyID      pgtype.UUID
	Name          *string
	AmountMinor   *int64
	CurrencyCode  *string
	CategoryID    pgtype.UUID
	AccountID     pgtype.UUID
	MemberID      pgtype.UUID
	IntervalCount *int32
	IntervalUnit  *string
	DayOfMonth    *int32
	DayOfWeek     *string
	NextDueOn     pgtype.Date
	EndOn         pgtype.Date
	AutoPost      *bool
	Active        *bool
}

func (q *Queries) UpdateRecurringPayment(ctx context.Context, arg UpdateRecurringPaymentParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, updateRecurringPayment,
		arg.ID,
		arg.FamilyID,
		arg.Name,
		arg.AmountMinor,
		arg.CurrencyCode,
		arg.CategoryID,
		arg.AccountID,
		arg.MemberID,
		arg.IntervalCount,
		arg.IntervalUnit,
		arg.DayOfMonth,
		arg.DayOfWeek,
		arg.NextDueOn,
		arg.EndOn,
		arg.AutoPost,
		arg.Active,
	)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Name,
		&i.AmountMinor,
		&i.CurrencyCode,
		&i.Type,
		&i.CategoryID,
		&i.AccountID,
		&i.MemberID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.DayOfMonth,
		&i.DayOfWeek,
		&i.NextDueOn,
		&i.EndOn,
		&i.AutoPost,
		&i.Active,
		&i.LastPostedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
