// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID                 pgtype.UUID
	FamilyID           pgtype.UUID
	OwnerUserID        pgtype.UUID
	NotebookID         pgtype.UUID
	ClientID           string
	Title              string
	Blocks             []byte
	BodyText           string
	Search             interface{}
	Starred            bool
	Archived           bool
	Version            int64
	LastEditedByUserID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type NoteActivity struct {
	ID          pgtype.UUID
	NoteID      pgtype.UUID
	ActorUserID pgtype.UUID
	Kind        int16
	Detail      string
	CreatedAt   pgtype.Timestamptz
}

type NoteComment struct {
	ID           pgtype.UUID
	NoteID       pgtype.UUID
	AuthorUserID pgtype.UUID
	Body         string
	Resolved     bool
	CreatedAt    pgtype.Timestamptz
}

type NoteShare struct {
	ID              pgtype.UUID
	NoteID          pgtype.UUID
	FamilyID        pgtype.UUID
	Subject         int16
	MemberUserID    pgtype.UUID
	Permission      int16
	GrantedByUserID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
}

type Notebook struct {
	ID          pgtype.UUID
	FamilyID    pgtype.UUID
	OwnerUserID pgtype.UUID
	ParentID    pgtype.UUID
	Name        string
	Archived    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type NotebookShare struct {
	ID              pgtype.UUID
	NotebookID      pgtype.UUID
	FamilyID        pgtype.UUID
	Subject         int16
	MemberUserID    pgtype.UUID
	Permission      int16
	GrantedByUserID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
}
