// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: states.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearChatState = `-- name: ClearChatState :execrows
DELETE FROM chat_states
WHERE bot = $1 AND telegram_user_id = $2
`

type ClearChatStateParams struct {
	Bot            string
	TelegramUserID int64
}

func (q *Queries) ClearChatState(ctx context.Context, arg ClearChatStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearChatState, arg.Bot, arg.TelegramUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredChatStates = `-- name: DeleteExpiredChatStates :execrows
DELETE FROM chat_states
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredChatStates(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredChatStates)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChatState = `-- name: GetChatState :one
SELECT bot, telegram_user_id, kind, payload, expires_at, updated_at FROM chat_states
WHERE bot = $1 AND telegram_user_id = $2 AND expires_at > NOW()
`

type GetChatStateParams struct {
	Bot            string
	TelegramUserID int64
}

func (q *Queries) GetChatState(ctx context.Context, arg GetChatStateParams) (ChatState, error) {
	row := q.db.QueryRow(ctx, getChatState, arg.Bot, arg.TelegramUserID)
	var i ChatState
	err := row.Scan(
		&i.Bot,
		&i.TelegramUserID,
		&i.Kind,
		&i.Payload,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertChatState = `-- name: UpsertChatState :one
INSERT INTO chat_states (bot, telegram_user_id, kind, payload, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (bot, telegram_user_id) DO UPDATE
SET kind       = EXCLUDED.kind,
    payload    = EXCLUDED.payload,
    expires_at = EXCLUDED.expires_at,
    updated_at = NOW()
RETURNING bot, telegram_user_id, kind, payload, expires_at, updated_at
`

type UpsertChatStateParams struct {
	Bot            string
	TelegramUserID int64
	Kind           string
	Payload        []byte
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) UpsertChatState(ctx context.Context, arg UpsertChatStateParams) (ChatState, error) {
	row := q.db.QueryRow(ctx, upsertChatState,
		arg.Bot,
		arg.TelegramUserID,
		arg.Kind,
		arg.Payload,
		arg.ExpiresAt,
	)
	var i ChatState
	err := row.Scan(
		&i.Bot,
		&i.TelegramUserID,
		&i.Kind,
		&i.Payload,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}
