// The repo-wide ESLint flat config. Packages and apps re-export this and add nothing unless
// the rule is genuinely local to them.
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.expo/**",
      "**/*.config.cjs",
      // Generated by `just proto` — lint findings there are unfixable by hand.
      "sdk/typescript/src/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // Unused args are normal in RN callbacks; unused locals are not.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // An `any` in the data layer defeats the point of generating a typed SDK.
      "@typescript-eslint/no-explicit-any": "error",
      eqeqeq: ["error", "smart"],
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },
);
