// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_grants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveLoginGrant = `-- name: ApproveLoginGrant :one
UPDATE login_grants
SET user_id = $1, approved_at = $2
WHERE user_code_hash = $3
  AND approved_at IS NULL
  AND denied_at IS NULL
  AND expires_at > $2
RETURNING id, kind, device_code_hash, user_code_hash, user_id, approved_at, denied_at, consumed_at, last_polled_at, expires_at, created_at
`

type ApproveLoginGrantParams struct {
	UserID       pgtype.UUID
	DecidedAt    pgtype.Timestamptz
	UserCodeHash string
}

func (q *Queries) ApproveLoginGrant(ctx context.Context, arg ApproveLoginGrantParams) (LoginGrant, error) {
	row := q.db.QueryRow(ctx, approveLoginGrant, arg.UserID, arg.DecidedAt, arg.UserCodeHash)
	var i LoginGrant
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.UserID,
		&i.ApprovedAt,
		&i.DeniedAt,
		&i.ConsumedAt,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeLoginGrant = `-- name: ConsumeLoginGrant :execrows
UPDATE login_grants
SET consumed_at = NOW()
WHERE id = $1
  AND approved_at IS NOT NULL
  AND denied_at IS NULL
  AND consumed_at IS NULL
`

func (q *Queries) ConsumeLoginGrant(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeLoginGrant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createLoginGrant = `-- name: CreateLoginGrant :one
INSERT INTO login_grants (kind, device_code_hash, user_code_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, kind, device_code_hash, user_code_hash, user_id, approved_at, denied_at, consumed_at, last_polled_at, expires_at, created_at
`

type CreateLoginGrantParams struct {
	Kind           string
	DeviceCodeHash string
	UserCodeHash   string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreateLoginGrant(ctx context.Context, arg CreateLoginGrantParams) (LoginGrant, error) {
	row := q.db.QueryRow(ctx, createLoginGrant,
		arg.Kind,
		arg.DeviceCodeHash,
		arg.UserCodeHash,
		arg.ExpiresAt,
	)
	var i LoginGrant
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.UserID,
		&i.ApprovedAt,
		&i.DeniedAt,
		&i.ConsumedAt,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredLoginGrants = `-- name: DeleteExpiredLoginGrants :execrows
DELETE FROM login_grants
WHERE expires_at < NOW() - interval '1 hour'
`

func (q *Queries) DeleteExpiredLoginGrants(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLoginGrants)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const denyLoginGrant = `-- name: DenyLoginGrant :execrows
UPDATE login_grants
SET user_id = $1, denied_at = $2
WHERE user_code_hash = $3
  AND approved_at IS NULL
  AND denied_at IS NULL
  AND expires_at > $2
`

type DenyLoginGrantParams struct {
	UserID       pgtype.UUID
	DecidedAt    pgtype.Timestamptz
	UserCodeHash string
}

func (q *Queries) DenyLoginGrant(ctx context.Context, arg DenyLoginGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, denyLoginGrant, arg.UserID, arg.DecidedAt, arg.UserCodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLoginGrantByDeviceCode = `-- name: GetLoginGrantByDeviceCode :one
SELECT id, kind, device_code_hash, user_code_hash, user_id, approved_at, denied_at, consumed_at, last_polled_at, expires_at, created_at FROM login_grants
WHERE device_code_hash = $1
`

func (q *Queries) GetLoginGrantByDeviceCode(ctx context.Context, deviceCodeHash string) (LoginGrant, error) {
	row := q.db.QueryRow(ctx, getLoginGrantByDeviceCode, deviceCodeHash)
	var i LoginGrant
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.UserID,
		&i.ApprovedAt,
		&i.DeniedAt,
		&i.ConsumedAt,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLoginGrantByUserCode = `-- name: GetLoginGrantByUserCode :one
SELECT id, kind, device_code_hash, user_code_hash, user_id, approved_at, denied_at, consumed_at, last_polled_at, expires_at, created_at FROM login_grants
WHERE user_code_hash = $1
`

func (q *Queries) GetLoginGrantByUserCode(ctx context.Context, userCodeHash string) (LoginGrant, error) {
	row := q.db.QueryRow(ctx, getLoginGrantByUserCode, userCodeHash)
	var i LoginGrant
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DeviceCodeHash,
		&i.UserCodeHash,
		&i.UserID,
		&i.ApprovedAt,
		&i.DeniedAt,
		&i.ConsumedAt,
		&i.LastPolledAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchLoginGrant = `-- name: TouchLoginGrant :execrows
UPDATE login_grants
SET last_polled_at = $1
WHERE id = $2
  AND (last_polled_at IS NULL OR last_polled_at <= $3)
`

type TouchLoginGrantParams struct {
	PolledAt pgtype.Timestamptz
	ID       pgtype.UUID
	NotAfter pgtype.Timestamptz
}

func (q *Queries) TouchLoginGrant(ctx context.Context, arg TouchLoginGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchLoginGrant, arg.PolledAt, arg.ID, arg.NotAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
