// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: notes/v1/notes.proto

package notesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nnc/family-manager/sdk/go/notes/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotesServiceName is the fully-qualified name of the NotesService service.
	NotesServiceName = "notes.v1.NotesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotesServiceCreateNotebookProcedure is the fully-qualified name of the NotesService's
	// CreateNotebook RPC.
	NotesServiceCreateNotebookProcedure = "/notes.v1.NotesService/CreateNotebook"
	// NotesServiceListNotebooksProcedure is the fully-qualified name of the NotesService's
	// ListNotebooks RPC.
	NotesServiceListNotebooksProcedure = "/notes.v1.NotesService/ListNotebooks"
	// NotesServiceUpdateNotebookProcedure is the fully-qualified name of the NotesService's
	// UpdateNotebook RPC.
	NotesServiceUpdateNotebookProcedure = "/notes.v1.NotesService/UpdateNotebook"
	// NotesServiceDeleteNotebookProcedure is the fully-qualified name of the NotesService's
	// DeleteNotebook RPC.
	NotesServiceDeleteNotebookProcedure = "/notes.v1.NotesService/DeleteNotebook"
	// NotesServiceCreateNoteProcedure is the fully-qualified name of the NotesService's CreateNote RPC.
	NotesServiceCreateNoteProcedure = "/notes.v1.NotesService/CreateNote"
	// NotesServiceGetNoteProcedure is the fully-qualified name of the NotesService's GetNote RPC.
	NotesServiceGetNoteProcedure = "/notes.v1.NotesService/GetNote"
	// NotesServiceListNotesProcedure is the fully-qualified name of the NotesService's ListNotes RPC.
	NotesServiceListNotesProcedure = "/notes.v1.NotesService/ListNotes"
	// NotesServiceUpdateNoteProcedure is the fully-qualified name of the NotesService's UpdateNote RPC.
	NotesServiceUpdateNoteProcedure = "/notes.v1.NotesService/UpdateNote"
	// NotesServiceMoveNoteProcedure is the fully-qualified name of the NotesService's MoveNote RPC.
	NotesServiceMoveNoteProcedure = "/notes.v1.NotesService/MoveNote"
	// NotesServiceToggleStarProcedure is the fully-qualified name of the NotesService's ToggleStar RPC.
	NotesServiceToggleStarProcedure = "/notes.v1.NotesService/ToggleStar"
	// NotesServiceArchiveNoteProcedure is the fully-qualified name of the NotesService's ArchiveNote
	// RPC.
	NotesServiceArchiveNoteProcedure = "/notes.v1.NotesService/ArchiveNote"
	// NotesServiceDeleteNoteProcedure is the fully-qualified name of the NotesService's DeleteNote RPC.
	NotesServiceDeleteNoteProcedure = "/notes.v1.NotesService/DeleteNote"
	// NotesServiceUploadNoteImageProcedure is the fully-qualified name of the NotesService's
	// UploadNoteImage RPC.
	NotesServiceUploadNoteImageProcedure = "/notes.v1.NotesService/UploadNoteImage"
	// NotesServiceSearchProcedure is the fully-qualified name of the NotesService's Search RPC.
	NotesServiceSearchProcedure = "/notes.v1.NotesService/Search"
	// NotesServiceShareNoteProcedure is the fully-qualified name of the NotesService's ShareNote RPC.
	NotesServiceShareNoteProcedure = "/notes.v1.NotesService/ShareNote"
	// NotesServiceShareNotebookProcedure is the fully-qualified name of the NotesService's
	// ShareNotebook RPC.
	NotesServiceShareNotebookProcedure = "/notes.v1.NotesService/ShareNotebook"
	// NotesServiceUnshareProcedure is the fully-qualified name of the NotesService's Unshare RPC.
	NotesServiceUnshareProcedure = "/notes.v1.NotesService/Unshare"
	// NotesServiceListSharesProcedure is the fully-qualified name of the NotesService's ListShares RPC.
	NotesServiceListSharesProcedure = "/notes.v1.NotesService/ListShares"
	// NotesServiceListSharedWithMeProcedure is the fully-qualified name of the NotesService's
	// ListSharedWithMe RPC.
	NotesServiceListSharedWithMeProcedure = "/notes.v1.NotesService/ListSharedWithMe"
	// NotesServiceAddCommentProcedure is the fully-qualified name of the NotesService's AddComment RPC.
	NotesServiceAddCommentProcedure = "/notes.v1.NotesService/AddComment"
	// NotesServiceListCommentsProcedure is the fully-qualified name of the NotesService's ListComments
	// RPC.
	NotesServiceListCommentsProcedure = "/notes.v1.NotesService/ListComments"
	// NotesServiceResolveCommentProcedure is the fully-qualified name of the NotesService's
	// ResolveComment RPC.
	NotesServiceResolveCommentProcedure = "/notes.v1.NotesService/ResolveComment"
	// NotesServiceListActivityProcedure is the fully-qualified name of the NotesService's ListActivity
	// RPC.
	NotesServiceListActivityProcedure = "/notes.v1.NotesService/ListActivity"
)

// NotesServiceClient is a client for the notes.v1.NotesService service.
type NotesServiceClient interface {
	// --- notebooks ----------------------------------------------------------
	CreateNotebook(context.Context, *connect.Request[v1.CreateNotebookRequest]) (*connect.Response[v1.CreateNotebookResponse], error)
	ListNotebooks(context.Context, *connect.Request[v1.ListNotebooksRequest]) (*connect.Response[v1.ListNotebooksResponse], error)
	UpdateNotebook(context.Context, *connect.Request[v1.UpdateNotebookRequest]) (*connect.Response[v1.UpdateNotebookResponse], error)
	// DeleteNotebook refuses while the notebook still holds notes, rather than cascading:
	// a mis-tapped notebook delete must not be able to take a hundred notes with it.
	DeleteNotebook(context.Context, *connect.Request[v1.DeleteNotebookRequest]) (*connect.Response[v1.DeleteNotebookResponse], error)
	// --- notes --------------------------------------------------------------
	CreateNote(context.Context, *connect.Request[v1.CreateNoteRequest]) (*connect.Response[v1.CreateNoteResponse], error)
	GetNote(context.Context, *connect.Request[v1.GetNoteRequest]) (*connect.Response[v1.GetNoteResponse], error)
	ListNotes(context.Context, *connect.Request[v1.ListNotesRequest]) (*connect.Response[v1.ListNotesResponse], error)
	// UpdateNote writes the whole note — title plus the full block array. Blocks are a
	// document, not rows: a partial update would need a diff protocol on both sides, and the
	// documents here are small enough that sending all of them is cheaper than agreeing on
	// what changed. expected_version makes the write conditional; see the field's comment.
	UpdateNote(context.Context, *connect.Request[v1.UpdateNoteRequest]) (*connect.Response[v1.UpdateNoteResponse], error)
	MoveNote(context.Context, *connect.Request[v1.MoveNoteRequest]) (*connect.Response[v1.MoveNoteResponse], error)
	ToggleStar(context.Context, *connect.Request[v1.ToggleStarRequest]) (*connect.Response[v1.ToggleStarResponse], error)
	// ArchiveNote sets or clears Note.archived — the rail's Archive row, and the way back out
	// of it. Archiving is not deleting: the note keeps its blocks, its comments and its shares,
	// and only leaves the lists that do not ask for it. It is a write on the shared row like
	// starring, so it needs EDIT and not merely sight of the note.
	ArchiveNote(context.Context, *connect.Request[v1.ArchiveNoteRequest]) (*connect.Response[v1.ArchiveNoteResponse], error)
	DeleteNote(context.Context, *connect.Request[v1.DeleteNoteRequest]) (*connect.Response[v1.DeleteNoteResponse], error)
	// UploadNoteImage stores an image block's bytes and returns its URL. Sent as raw bytes
	// over Connect/JSON (base64 on the wire) rather than a presigned-URL flow — the same
	// tradeoff RecipesService.UploadRecipeImage makes, for the same reason: one round trip.
	//
	// NOT EXPOSED IN v1. The product ships no image blocks and the service is deployed with no
	// storage configured, so this procedure answers with an error and no bucket is ever created.
	// The reason is libs/go/storage: EnsureBucket sets an anonymous-read policy on every bucket
	// it makes, so the URL this rpc returns would be fetchable by anyone holding it — including
	// for a note that was never shared, and still after a share is revoked. A note is private by
	// default (see the service comment above); an object store that is public by default cannot
	// hold that note's photo. Wiring image blocks up needs presigned reads in libs/go/storage
	// first, at which point this procedure works as written.
	//
	// It stays in the contract because removing it is a breaking change that buys nothing: an
	// rpc nobody calls costs a generated method, while deleting one costs every client a
	// regeneration and `buf breaking` a waiver.
	UploadNoteImage(context.Context, *connect.Request[v1.UploadNoteImageRequest]) (*connect.Response[v1.UploadNoteImageResponse], error)
	// --- search -------------------------------------------------------------
	// Search is the ⌘K palette: one query across notes, the tasks inside them, and notebook
	// names, ranked server-side. The app never filters a full note list client-side — that
	// stops working at the first notebook nobody has opened yet.
	Search(context.Context, *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error)
	// --- sharing ------------------------------------------------------------
	ShareNote(context.Context, *connect.Request[v1.ShareNoteRequest]) (*connect.Response[v1.ShareNoteResponse], error)
	ShareNotebook(context.Context, *connect.Request[v1.ShareNotebookRequest]) (*connect.Response[v1.ShareNotebookResponse], error)
	Unshare(context.Context, *connect.Request[v1.UnshareRequest]) (*connect.Response[v1.UnshareResponse], error)
	ListShares(context.Context, *connect.Request[v1.ListSharesRequest]) (*connect.Response[v1.ListSharesResponse], error)
	// ListSharedWithMe is the sidebar's "Shared with me": everything the caller can see that
	// they do not own.
	ListSharedWithMe(context.Context, *connect.Request[v1.ListSharedWithMeRequest]) (*connect.Response[v1.ListSharedWithMeResponse], error)
	// --- comments -----------------------------------------------------------
	AddComment(context.Context, *connect.Request[v1.AddCommentRequest]) (*connect.Response[v1.AddCommentResponse], error)
	ListComments(context.Context, *connect.Request[v1.ListCommentsRequest]) (*connect.Response[v1.ListCommentsResponse], error)
	ResolveComment(context.Context, *connect.Request[v1.ResolveCommentRequest]) (*connect.Response[v1.ResolveCommentResponse], error)
	// --- activity -----------------------------------------------------------
	ListActivity(context.Context, *connect.Request[v1.ListActivityRequest]) (*connect.Response[v1.ListActivityResponse], error)
}

// NewNotesServiceClient constructs a client for the notes.v1.NotesService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notesServiceMethods := v1.File_notes_v1_notes_proto.Services().ByName("NotesService").Methods()
	return &notesServiceClient{
		createNotebook: connect.NewClient[v1.CreateNotebookRequest, v1.CreateNotebookResponse](
			httpClient,
			baseURL+NotesServiceCreateNotebookProcedure,
			connect.WithSchema(notesServiceMethods.ByName("CreateNotebook")),
			connect.WithClientOptions(opts...),
		),
		listNotebooks: connect.NewClient[v1.ListNotebooksRequest, v1.ListNotebooksResponse](
			httpClient,
			baseURL+NotesServiceListNotebooksProcedure,
			connect.WithSchema(notesServiceMethods.ByName("ListNotebooks")),
			connect.WithClientOptions(opts...),
		),
		updateNotebook: connect.NewClient[v1.UpdateNotebookRequest, v1.UpdateNotebookResponse](
			httpClient,
			baseURL+NotesServiceUpdateNotebookProcedure,
			connect.WithSchema(notesServiceMethods.ByName("UpdateNotebook")),
			connect.WithClientOptions(opts...),
		),
		deleteNotebook: connect.NewClient[v1.DeleteNotebookRequest, v1.DeleteNotebookResponse](
			httpClient,
			baseURL+NotesServiceDeleteNotebookProcedure,
			connect.WithSchema(notesServiceMethods.ByName("DeleteNotebook")),
			connect.WithClientOptions(opts...),
		),
		createNote: connect.NewClient[v1.CreateNoteRequest, v1.CreateNoteResponse](
			httpClient,
			baseURL+NotesServiceCreateNoteProcedure,
			connect.WithSchema(notesServiceMethods.ByName("CreateNote")),
			connect.WithClientOptions(opts...),
		),
		getNote: connect.NewClient[v1.GetNoteRequest, v1.GetNoteResponse](
			httpClient,
			baseURL+NotesServiceGetNoteProcedure,
			connect.WithSchema(notesServiceMethods.ByName("GetNote")),
			connect.WithClientOptions(opts...),
		),
		listNotes: connect.NewClient[v1.ListNotesRequest, v1.ListNotesResponse](
			httpClient,
			baseURL+NotesServiceListNotesProcedure,
			connect.WithSchema(notesServiceMethods.ByName("ListNotes")),
			connect.WithClientOptions(opts...),
		),
		updateNote: connect.NewClient[v1.UpdateNoteRequest, v1.UpdateNoteResponse](
			httpClient,
			baseURL+NotesServiceUpdateNoteProcedure,
			connect.WithSchema(notesServiceMethods.ByName("UpdateNote")),
			connect.WithClientOptions(opts...),
		),
		moveNote: connect.NewClient[v1.MoveNoteRequest, v1.MoveNoteResponse](
			httpClient,
			baseURL+NotesServiceMoveNoteProcedure,
			connect.WithSchema(notesServiceMethods.ByName("MoveNote")),
			connect.WithClientOptions(opts...),
		),
		toggleStar: connect.NewClient[v1.ToggleStarRequest, v1.ToggleStarResponse](
			httpClient,
			baseURL+NotesServiceToggleStarProcedure,
			connect.WithSchema(notesServiceMethods.ByName("ToggleStar")),
			connect.WithClientOptions(opts...),
		),
		archiveNote: connect.NewClient[v1.ArchiveNoteRequest, v1.ArchiveNoteResponse](
			httpClient,
			baseURL+NotesServiceArchiveNoteProcedure,
			connect.WithSchema(notesServiceMethods.ByName("ArchiveNote")),
			connect.WithClientOptions(opts...),
		),
		deleteNote: connect.NewClient[v1.DeleteNoteRequest, v1.DeleteNoteResponse](
			httpClient,
			baseURL+NotesServiceDeleteNoteProcedure,
			connect.WithSchema(notesServiceMethods.ByName("DeleteNote")),
			connect.WithClientOptions(opts...),
		),
		uploadNoteImage: connect.NewClient[v1.UploadNoteImageRequest, v1.UploadNoteImageResponse](
			httpClient,
			baseURL+NotesServiceUploadNoteImageProcedure,
			connect.WithSchema(notesServiceMethods.ByName("UploadNoteImage")),
			connect.WithClientOptions(opts...),
		),
		search: connect.NewClient[v1.SearchRequest, v1.SearchResponse](
			httpClient,
			baseURL+NotesServiceSearchProcedure,
			connect.WithSchema(notesServiceMethods.ByName("Search")),
			connect.WithClientOptions(opts...),
		),
		shareNote: connect.NewClient[v1.ShareNoteRequest, v1.ShareNoteResponse](
			httpClient,
			baseURL+NotesServiceShareNoteProcedure,
			connect.WithSchema(notesServiceMethods.ByName("ShareNote")),
			connect.WithClientOptions(opts...),
		),
		shareNotebook: connect.NewClient[v1.ShareNotebookRequest, v1.ShareNotebookResponse](
			httpClient,
			baseURL+NotesServiceShareNotebookProcedure,
			connect.WithSchema(notesServiceMethods.ByName("ShareNotebook")),
			connect.WithClientOptions(opts...),
		),
		unshare: connect.NewClient[v1.UnshareRequest, v1.UnshareResponse](
			httpClient,
			baseURL+NotesServiceUnshareProcedure,
			connect.WithSchema(notesServiceMethods.ByName("Unshare")),
			connect.WithClientOptions(opts...),
		),
		listShares: connect.NewClient[v1.ListSharesRequest, v1.ListSharesResponse](
			httpClient,
			baseURL+NotesServiceListSharesProcedure,
			connect.WithSchema(notesServiceMethods.ByName("ListShares")),
			connect.WithClientOptions(opts...),
		),
		listSharedWithMe: connect.NewClient[v1.ListSharedWithMeRequest, v1.ListSharedWithMeResponse](
			httpClient,
			baseURL+NotesServiceListSharedWithMeProcedure,
			connect.WithSchema(notesServiceMethods.ByName("ListSharedWithMe")),
			connect.WithClientOptions(opts...),
		),
		addComment: connect.NewClient[v1.AddCommentRequest, v1.AddCommentResponse](
			httpClient,
			baseURL+NotesServiceAddCommentProcedure,
			connect.WithSchema(notesServiceMethods.ByName("AddComment")),
			connect.WithClientOptions(opts...),
		),
		listComments: connect.NewClient[v1.ListCommentsRequest, v1.ListCommentsResponse](
			httpClient,
			baseURL+NotesServiceListCommentsProcedure,
			connect.WithSchema(notesServiceMethods.ByName("ListComments")),
			connect.WithClientOptions(opts...),
		),
		resolveComment: connect.NewClient[v1.ResolveCommentRequest, v1.ResolveCommentResponse](
			httpClient,
			baseURL+NotesServiceResolveCommentProcedure,
			connect.WithSchema(notesServiceMethods.ByName("ResolveComment")),
			connect.WithClientOptions(opts...),
		),
		listActivity: connect.NewClient[v1.ListActivityRequest, v1.ListActivityResponse](
			httpClient,
			baseURL+NotesServiceListActivityProcedure,
			connect.WithSchema(notesServiceMethods.ByName("ListActivity")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notesServiceClient implements NotesServiceClient.
type notesServiceClient struct {
	createNotebook   *connect.Client[v1.CreateNotebookRequest, v1.CreateNotebookResponse]
	listNotebooks    *connect.Client[v1.ListNotebooksRequest, v1.ListNotebooksResponse]
	updateNotebook   *connect.Client[v1.UpdateNotebookRequest, v1.UpdateNotebookResponse]
	deleteNotebook   *connect.Client[v1.DeleteNotebookRequest, v1.DeleteNotebookResponse]
	createNote       *connect.Client[v1.CreateNoteRequest, v1.CreateNoteResponse]
	getNote          *connect.Client[v1.GetNoteRequest, v1.GetNoteResponse]
	listNotes        *connect.Client[v1.ListNotesRequest, v1.ListNotesResponse]
	updateNote       *connect.Client[v1.UpdateNoteRequest, v1.UpdateNoteResponse]
	moveNote         *connect.Client[v1.MoveNoteRequest, v1.MoveNoteResponse]
	toggleStar       *connect.Client[v1.ToggleStarRequest, v1.ToggleStarResponse]
	archiveNote      *connect.Client[v1.ArchiveNoteRequest, v1.ArchiveNoteResponse]
	deleteNote       *connect.Client[v1.DeleteNoteRequest, v1.DeleteNoteResponse]
	uploadNoteImage  *connect.Client[v1.UploadNoteImageRequest, v1.UploadNoteImageResponse]
	search           *connect.Client[v1.SearchRequest, v1.SearchResponse]
	shareNote        *connect.Client[v1.ShareNoteRequest, v1.ShareNoteResponse]
	shareNotebook    *connect.Client[v1.ShareNotebookRequest, v1.ShareNotebookResponse]
	unshare          *connect.Client[v1.UnshareRequest, v1.UnshareResponse]
	listShares       *connect.Client[v1.ListSharesRequest, v1.ListSharesResponse]
	listSharedWithMe *connect.Client[v1.ListSharedWithMeRequest, v1.ListSharedWithMeResponse]
	addComment       *connect.Client[v1.AddCommentRequest, v1.AddCommentResponse]
	listComments     *connect.Client[v1.ListCommentsRequest, v1.ListCommentsResponse]
	resolveComment   *connect.Client[v1.ResolveCommentRequest, v1.ResolveCommentResponse]
	listActivity     *connect.Client[v1.ListActivityRequest, v1.ListActivityResponse]
}

// CreateNotebook calls notes.v1.NotesService.CreateNotebook.
func (c *notesServiceClient) CreateNotebook(ctx context.Context, req *connect.Request[v1.CreateNotebookRequest]) (*connect.Response[v1.CreateNotebookResponse], error) {
	return c.createNotebook.CallUnary(ctx, req)
}

// ListNotebooks calls notes.v1.NotesService.ListNotebooks.
func (c *notesServiceClient) ListNotebooks(ctx context.Context, req *connect.Request[v1.ListNotebooksRequest]) (*connect.Response[v1.ListNotebooksResponse], error) {
	return c.listNotebooks.CallUnary(ctx, req)
}

// UpdateNotebook calls notes.v1.NotesService.UpdateNotebook.
func (c *notesServiceClient) UpdateNotebook(ctx context.Context, req *connect.Request[v1.UpdateNotebookRequest]) (*connect.Response[v1.UpdateNotebookResponse], error) {
	return c.updateNotebook.CallUnary(ctx, req)
}

// DeleteNotebook calls notes.v1.NotesService.DeleteNotebook.
func (c *notesServiceClient) DeleteNotebook(ctx context.Context, req *connect.Request[v1.DeleteNotebookRequest]) (*connect.Response[v1.DeleteNotebookResponse], error) {
	return c.deleteNotebook.CallUnary(ctx, req)
}

// CreateNote calls notes.v1.NotesService.CreateNote.
func (c *notesServiceClient) CreateNote(ctx context.Context, req *connect.Request[v1.CreateNoteRequest]) (*connect.Response[v1.CreateNoteResponse], error) {
	return c.createNote.CallUnary(ctx, req)
}

// GetNote calls notes.v1.NotesService.GetNote.
func (c *notesServiceClient) GetNote(ctx context.Context, req *connect.Request[v1.GetNoteRequest]) (*connect.Response[v1.GetNoteResponse], error) {
	return c.getNote.CallUnary(ctx, req)
}

// ListNotes calls notes.v1.NotesService.ListNotes.
func (c *notesServiceClient) ListNotes(ctx context.Context, req *connect.Request[v1.ListNotesRequest]) (*connect.Response[v1.ListNotesResponse], error) {
	return c.listNotes.CallUnary(ctx, req)
}

// UpdateNote calls notes.v1.NotesService.UpdateNote.
func (c *notesServiceClient) UpdateNote(ctx context.Context, req *connect.Request[v1.UpdateNoteRequest]) (*connect.Response[v1.UpdateNoteResponse], error) {
	return c.updateNote.CallUnary(ctx, req)
}

// MoveNote calls notes.v1.NotesService.MoveNote.
func (c *notesServiceClient) MoveNote(ctx context.Context, req *connect.Request[v1.MoveNoteRequest]) (*connect.Response[v1.MoveNoteResponse], error) {
	return c.moveNote.CallUnary(ctx, req)
}

// ToggleStar calls notes.v1.NotesService.ToggleStar.
func (c *notesServiceClient) ToggleStar(ctx context.Context, req *connect.Request[v1.ToggleStarRequest]) (*connect.Response[v1.ToggleStarResponse], error) {
	return c.toggleStar.CallUnary(ctx, req)
}

// ArchiveNote calls notes.v1.NotesService.ArchiveNote.
func (c *notesServiceClient) ArchiveNote(ctx context.Context, req *connect.Request[v1.ArchiveNoteRequest]) (*connect.Response[v1.ArchiveNoteResponse], error) {
	return c.archiveNote.CallUnary(ctx, req)
}

// DeleteNote calls notes.v1.NotesService.DeleteNote.
func (c *notesServiceClient) DeleteNote(ctx context.Context, req *connect.Request[v1.DeleteNoteRequest]) (*connect.Response[v1.DeleteNoteResponse], error) {
	return c.deleteNote.CallUnary(ctx, req)
}

// UploadNoteImage calls notes.v1.NotesService.UploadNoteImage.
func (c *notesServiceClient) UploadNoteImage(ctx context.Context, req *connect.Request[v1.UploadNoteImageRequest]) (*connect.Response[v1.UploadNoteImageResponse], error) {
	return c.uploadNoteImage.CallUnary(ctx, req)
}

// Search calls notes.v1.NotesService.Search.
func (c *notesServiceClient) Search(ctx context.Context, req *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error) {
	return c.search.CallUnary(ctx, req)
}

// ShareNote calls notes.v1.NotesService.ShareNote.
func (c *notesServiceClient) ShareNote(ctx context.Context, req *connect.Request[v1.ShareNoteRequest]) (*connect.Response[v1.ShareNoteResponse], error) {
	return c.shareNote.CallUnary(ctx, req)
}

// ShareNotebook calls notes.v1.NotesService.ShareNotebook.
func (c *notesServiceClient) ShareNotebook(ctx context.Context, req *connect.Request[v1.ShareNotebookRequest]) (*connect.Response[v1.ShareNotebookResponse], error) {
	return c.shareNotebook.CallUnary(ctx, req)
}

// Unshare calls notes.v1.NotesService.Unshare.
func (c *notesServiceClient) Unshare(ctx context.Context, req *connect.Request[v1.UnshareRequest]) (*connect.Response[v1.UnshareResponse], error) {
	return c.unshare.CallUnary(ctx, req)
}

// ListShares calls notes.v1.NotesService.ListShares.
func (c *notesServiceClient) ListShares(ctx context.Context, req *connect.Request[v1.ListSharesRequest]) (*connect.Response[v1.ListSharesResponse], error) {
	return c.listShares.CallUnary(ctx, req)
}

// ListSharedWithMe calls notes.v1.NotesService.ListSharedWithMe.
func (c *notesServiceClient) ListSharedWithMe(ctx context.Context, req *connect.Request[v1.ListSharedWithMeRequest]) (*connect.Response[v1.ListSharedWithMeResponse], error) {
	return c.listSharedWithMe.CallUnary(ctx, req)
}

// AddComment calls notes.v1.NotesService.AddComment.
func (c *notesServiceClient) AddComment(ctx context.Context, req *connect.Request[v1.AddCommentRequest]) (*connect.Response[v1.AddCommentResponse], error) {
	return c.addComment.CallUnary(ctx, req)
}

// ListComments calls notes.v1.NotesService.ListComments.
func (c *notesServiceClient) ListComments(ctx context.Context, req *connect.Request[v1.ListCommentsRequest]) (*connect.Response[v1.ListCommentsResponse], error) {
	return c.listComments.CallUnary(ctx, req)
}

// ResolveComment calls notes.v1.NotesService.ResolveComment.
func (c *notesServiceClient) ResolveComment(ctx context.Context, req *connect.Request[v1.ResolveCommentRequest]) (*connect.Response[v1.ResolveCommentResponse], error) {
	return c.resolveComment.CallUnary(ctx, req)
}

// ListActivity calls notes.v1.NotesService.ListActivity.
func (c *notesServiceClient) ListActivity(ctx context.Context, req *connect.Request[v1.ListActivityRequest]) (*connect.Response[v1.ListActivityResponse], error) {
	return c.listActivity.CallUnary(ctx, req)
}

// NotesServiceHandler is an implementation of the notes.v1.NotesService service.
type NotesServiceHandler interface {
	// --- notebooks ----------------------------------------------------------
	CreateNotebook(context.Context, *connect.Request[v1.CreateNotebookRequest]) (*connect.Response[v1.CreateNotebookResponse], error)
	ListNotebooks(context.Context, *connect.Request[v1.ListNotebooksRequest]) (*connect.Response[v1.ListNotebooksResponse], error)
	UpdateNotebook(context.Context, *connect.Request[v1.UpdateNotebookRequest]) (*connect.Response[v1.UpdateNotebookResponse], error)
	// DeleteNotebook refuses while the notebook still holds notes, rather than cascading:
	// a mis-tapped notebook delete must not be able to take a hundred notes with it.
	DeleteNotebook(context.Context, *connect.Request[v1.DeleteNotebookRequest]) (*connect.Response[v1.DeleteNotebookResponse], error)
	// --- notes --------------------------------------------------------------
	CreateNote(context.Context, *connect.Request[v1.CreateNoteRequest]) (*connect.Response[v1.CreateNoteResponse], error)
	GetNote(context.Context, *connect.Request[v1.GetNoteRequest]) (*connect.Response[v1.GetNoteResponse], error)
	ListNotes(context.Context, *connect.Request[v1.ListNotesRequest]) (*connect.Response[v1.ListNotesResponse], error)
	// UpdateNote writes the whole note — title plus the full block array. Blocks are a
	// document, not rows: a partial update would need a diff protocol on both sides, and the
	// documents here are small enough that sending all of them is cheaper than agreeing on
	// what changed. expected_version makes the write conditional; see the field's comment.
	UpdateNote(context.Context, *connect.Request[v1.UpdateNoteRequest]) (*connect.Response[v1.UpdateNoteResponse], error)
	MoveNote(context.Context, *connect.Request[v1.MoveNoteRequest]) (*connect.Response[v1.MoveNoteResponse], error)
	ToggleStar(context.Context, *connect.Request[v1.ToggleStarRequest]) (*connect.Response[v1.ToggleStarResponse], error)
	// ArchiveNote sets or clears Note.archived — the rail's Archive row, and the way back out
	// of it. Archiving is not deleting: the note keeps its blocks, its comments and its shares,
	// and only leaves the lists that do not ask for it. It is a write on the shared row like
	// starring, so it needs EDIT and not merely sight of the note.
	ArchiveNote(context.Context, *connect.Request[v1.ArchiveNoteRequest]) (*connect.Response[v1.ArchiveNoteResponse], error)
	DeleteNote(context.Context, *connect.Request[v1.DeleteNoteRequest]) (*connect.Response[v1.DeleteNoteResponse], error)
	// UploadNoteImage stores an image block's bytes and returns its URL. Sent as raw bytes
	// over Connect/JSON (base64 on the wire) rather than a presigned-URL flow — the same
	// tradeoff RecipesService.UploadRecipeImage makes, for the same reason: one round trip.
	//
	// NOT EXPOSED IN v1. The product ships no image blocks and the service is deployed with no
	// storage configured, so this procedure answers with an error and no bucket is ever created.
	// The reason is libs/go/storage: EnsureBucket sets an anonymous-read policy on every bucket
	// it makes, so the URL this rpc returns would be fetchable by anyone holding it — including
	// for a note that was never shared, and still after a share is revoked. A note is private by
	// default (see the service comment above); an object store that is public by default cannot
	// hold that note's photo. Wiring image blocks up needs presigned reads in libs/go/storage
	// first, at which point this procedure works as written.
	//
	// It stays in the contract because removing it is a breaking change that buys nothing: an
	// rpc nobody calls costs a generated method, while deleting one costs every client a
	// regeneration and `buf breaking` a waiver.
	UploadNoteImage(context.Context, *connect.Request[v1.UploadNoteImageRequest]) (*connect.Response[v1.UploadNoteImageResponse], error)
	// --- search -------------------------------------------------------------
	// Search is the ⌘K palette: one query across notes, the tasks inside them, and notebook
	// names, ranked server-side. The app never filters a full note list client-side — that
	// stops working at the first notebook nobody has opened yet.
	Search(context.Context, *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error)
	// --- sharing ------------------------------------------------------------
	ShareNote(context.Context, *connect.Request[v1.ShareNoteRequest]) (*connect.Response[v1.ShareNoteResponse], error)
	ShareNotebook(context.Context, *connect.Request[v1.ShareNotebookRequest]) (*connect.Response[v1.ShareNotebookResponse], error)
	Unshare(context.Context, *connect.Request[v1.UnshareRequest]) (*connect.Response[v1.UnshareResponse], error)
	ListShares(context.Context, *connect.Request[v1.ListSharesRequest]) (*connect.Response[v1.ListSharesResponse], error)
	// ListSharedWithMe is the sidebar's "Shared with me": everything the caller can see that
	// they do not own.
	ListSharedWithMe(context.Context, *connect.Request[v1.ListSharedWithMeRequest]) (*connect.Response[v1.ListSharedWithMeResponse], error)
	// --- comments -----------------------------------------------------------
	AddComment(context.Context, *connect.Request[v1.AddCommentRequest]) (*connect.Response[v1.AddCommentResponse], error)
	ListComments(context.Context, *connect.Request[v1.ListCommentsRequest]) (*connect.Response[v1.ListCommentsResponse], error)
	ResolveComment(context.Context, *connect.Request[v1.ResolveCommentRequest]) (*connect.Response[v1.ResolveCommentResponse], error)
	// --- activity -----------------------------------------------------------
	ListActivity(context.Context, *connect.Request[v1.ListActivityRequest]) (*connect.Response[v1.ListActivityResponse], error)
}

// NewNotesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotesServiceHandler(svc NotesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notesServiceMethods := v1.File_notes_v1_notes_proto.Services().ByName("NotesService").Methods()
	notesServiceCreateNotebookHandler := connect.NewUnaryHandler(
		NotesServiceCreateNotebookProcedure,
		svc.CreateNotebook,
		connect.WithSchema(notesServiceMethods.ByName("CreateNotebook")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceListNotebooksHandler := connect.NewUnaryHandler(
		NotesServiceListNotebooksProcedure,
		svc.ListNotebooks,
		connect.WithSchema(notesServiceMethods.ByName("ListNotebooks")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceUpdateNotebookHandler := connect.NewUnaryHandler(
		NotesServiceUpdateNotebookProcedure,
		svc.UpdateNotebook,
		connect.WithSchema(notesServiceMethods.ByName("UpdateNotebook")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceDeleteNotebookHandler := connect.NewUnaryHandler(
		NotesServiceDeleteNotebookProcedure,
		svc.DeleteNotebook,
		connect.WithSchema(notesServiceMethods.ByName("DeleteNotebook")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceCreateNoteHandler := connect.NewUnaryHandler(
		NotesServiceCreateNoteProcedure,
		svc.CreateNote,
		connect.WithSchema(notesServiceMethods.ByName("CreateNote")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceGetNoteHandler := connect.NewUnaryHandler(
		NotesServiceGetNoteProcedure,
		svc.GetNote,
		connect.WithSchema(notesServiceMethods.ByName("GetNote")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceListNotesHandler := connect.NewUnaryHandler(
		NotesServiceListNotesProcedure,
		svc.ListNotes,
		connect.WithSchema(notesServiceMethods.ByName("ListNotes")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceUpdateNoteHandler := connect.NewUnaryHandler(
		NotesServiceUpdateNoteProcedure,
		svc.UpdateNote,
		connect.WithSchema(notesServiceMethods.ByName("UpdateNote")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceMoveNoteHandler := connect.NewUnaryHandler(
		NotesServiceMoveNoteProcedure,
		svc.MoveNote,
		connect.WithSchema(notesServiceMethods.ByName("MoveNote")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceToggleStarHandler := connect.NewUnaryHandler(
		NotesServiceToggleStarProcedure,
		svc.ToggleStar,
		connect.WithSchema(notesServiceMethods.ByName("ToggleStar")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceArchiveNoteHandler := connect.NewUnaryHandler(
		NotesServiceArchiveNoteProcedure,
		svc.ArchiveNote,
		connect.WithSchema(notesServiceMethods.ByName("ArchiveNote")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceDeleteNoteHandler := connect.NewUnaryHandler(
		NotesServiceDeleteNoteProcedure,
		svc.DeleteNote,
		connect.WithSchema(notesServiceMethods.ByName("DeleteNote")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceUploadNoteImageHandler := connect.NewUnaryHandler(
		NotesServiceUploadNoteImageProcedure,
		svc.UploadNoteImage,
		connect.WithSchema(notesServiceMethods.ByName("UploadNoteImage")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceSearchHandler := connect.NewUnaryHandler(
		NotesServiceSearchProcedure,
		svc.Search,
		connect.WithSchema(notesServiceMethods.ByName("Search")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceShareNoteHandler := connect.NewUnaryHandler(
		NotesServiceShareNoteProcedure,
		svc.ShareNote,
		connect.WithSchema(notesServiceMethods.ByName("ShareNote")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceShareNotebookHandler := connect.NewUnaryHandler(
		NotesServiceShareNotebookProcedure,
		svc.ShareNotebook,
		connect.WithSchema(notesServiceMethods.ByName("ShareNotebook")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceUnshareHandler := connect.NewUnaryHandler(
		NotesServiceUnshareProcedure,
		svc.Unshare,
		connect.WithSchema(notesServiceMethods.ByName("Unshare")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceListSharesHandler := connect.NewUnaryHandler(
		NotesServiceListSharesProcedure,
		svc.ListShares,
		connect.WithSchema(notesServiceMethods.ByName("ListShares")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceListSharedWithMeHandler := connect.NewUnaryHandler(
		NotesServiceListSharedWithMeProcedure,
		svc.ListSharedWithMe,
		connect.WithSchema(notesServiceMethods.ByName("ListSharedWithMe")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceAddCommentHandler := connect.NewUnaryHandler(
		NotesServiceAddCommentProcedure,
		svc.AddComment,
		connect.WithSchema(notesServiceMethods.ByName("AddComment")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceListCommentsHandler := connect.NewUnaryHandler(
		NotesServiceListCommentsProcedure,
		svc.ListComments,
		connect.WithSchema(notesServiceMethods.ByName("ListComments")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceResolveCommentHandler := connect.NewUnaryHandler(
		NotesServiceResolveCommentProcedure,
		svc.ResolveComment,
		connect.WithSchema(notesServiceMethods.ByName("ResolveComment")),
		connect.WithHandlerOptions(opts...),
	)
	notesServiceListActivityHandler := connect.NewUnaryHandler(
		NotesServiceListActivityProcedure,
		svc.ListActivity,
		connect.WithSchema(notesServiceMethods.ByName("ListActivity")),
		connect.WithHandlerOptions(opts...),
	)
	return "/notes.v1.NotesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotesServiceCreateNotebookProcedure:
			notesServiceCreateNotebookHandler.ServeHTTP(w, r)
		case NotesServiceListNotebooksProcedure:
			notesServiceListNotebooksHandler.ServeHTTP(w, r)
		case NotesServiceUpdateNotebookProcedure:
			notesServiceUpdateNotebookHandler.ServeHTTP(w, r)
		case NotesServiceDeleteNotebookProcedure:
			notesServiceDeleteNotebookHandler.ServeHTTP(w, r)
		case NotesServiceCreateNoteProcedure:
			notesServiceCreateNoteHandler.ServeHTTP(w, r)
		case NotesServiceGetNoteProcedure:
			notesServiceGetNoteHandler.ServeHTTP(w, r)
		case NotesServiceListNotesProcedure:
			notesServiceListNotesHandler.ServeHTTP(w, r)
		case NotesServiceUpdateNoteProcedure:
			notesServiceUpdateNoteHandler.ServeHTTP(w, r)
		case NotesServiceMoveNoteProcedure:
			notesServiceMoveNoteHandler.ServeHTTP(w, r)
		case NotesServiceToggleStarProcedure:
			notesServiceToggleStarHandler.ServeHTTP(w, r)
		case NotesServiceArchiveNoteProcedure:
			notesServiceArchiveNoteHandler.ServeHTTP(w, r)
		case NotesServiceDeleteNoteProcedure:
			notesServiceDeleteNoteHandler.ServeHTTP(w, r)
		case NotesServiceUploadNoteImageProcedure:
			notesServiceUploadNoteImageHandler.ServeHTTP(w, r)
		case NotesServiceSearchProcedure:
			notesServiceSearchHandler.ServeHTTP(w, r)
		case NotesServiceShareNoteProcedure:
			notesServiceShareNoteHandler.ServeHTTP(w, r)
		case NotesServiceShareNotebookProcedure:
			notesServiceShareNotebookHandler.ServeHTTP(w, r)
		case NotesServiceUnshareProcedure:
			notesServiceUnshareHandler.ServeHTTP(w, r)
		case NotesServiceListSharesProcedure:
			notesServiceListSharesHandler.ServeHTTP(w, r)
		case NotesServiceListSharedWithMeProcedure:
			notesServiceListSharedWithMeHandler.ServeHTTP(w, r)
		case NotesServiceAddCommentProcedure:
			notesServiceAddCommentHandler.ServeHTTP(w, r)
		case NotesServiceListCommentsProcedure:
			notesServiceListCommentsHandler.ServeHTTP(w, r)
		case NotesServiceResolveCommentProcedure:
			notesServiceResolveCommentHandler.ServeHTTP(w, r)
		case NotesServiceListActivityProcedure:
			notesServiceListActivityHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotesServiceHandler struct{}

func (UnimplementedNotesServiceHandler) CreateNotebook(context.Context, *connect.Request[v1.CreateNotebookRequest]) (*connect.Response[v1.CreateNotebookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.CreateNotebook is not implemented"))
}

func (UnimplementedNotesServiceHandler) ListNotebooks(context.Context, *connect.Request[v1.ListNotebooksRequest]) (*connect.Response[v1.ListNotebooksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.ListNotebooks is not implemented"))
}

func (UnimplementedNotesServiceHandler) UpdateNotebook(context.Context, *connect.Request[v1.UpdateNotebookRequest]) (*connect.Response[v1.UpdateNotebookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.UpdateNotebook is not implemented"))
}

func (UnimplementedNotesServiceHandler) DeleteNotebook(context.Context, *connect.Request[v1.DeleteNotebookRequest]) (*connect.Response[v1.DeleteNotebookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.DeleteNotebook is not implemented"))
}

func (UnimplementedNotesServiceHandler) CreateNote(context.Context, *connect.Request[v1.CreateNoteRequest]) (*connect.Response[v1.CreateNoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.CreateNote is not implemented"))
}

func (UnimplementedNotesServiceHandler) GetNote(context.Context, *connect.Request[v1.GetNoteRequest]) (*connect.Response[v1.GetNoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.GetNote is not implemented"))
}

func (UnimplementedNotesServiceHandler) ListNotes(context.Context, *connect.Request[v1.ListNotesRequest]) (*connect.Response[v1.ListNotesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.ListNotes is not implemented"))
}

func (UnimplementedNotesServiceHandler) UpdateNote(context.Context, *connect.Request[v1.UpdateNoteRequest]) (*connect.Response[v1.UpdateNoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.UpdateNote is not implemented"))
}

func (UnimplementedNotesServiceHandler) MoveNote(context.Context, *connect.Request[v1.MoveNoteRequest]) (*connect.Response[v1.MoveNoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.MoveNote is not implemented"))
}

func (UnimplementedNotesServiceHandler) ToggleStar(context.Context, *connect.Request[v1.ToggleStarRequest]) (*connect.Response[v1.ToggleStarResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.ToggleStar is not implemented"))
}

func (UnimplementedNotesServiceHandler) ArchiveNote(context.Context, *connect.Request[v1.ArchiveNoteRequest]) (*connect.Response[v1.ArchiveNoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.ArchiveNote is not implemented"))
}

func (UnimplementedNotesServiceHandler) DeleteNote(context.Context, *connect.Request[v1.DeleteNoteRequest]) (*connect.Response[v1.DeleteNoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.DeleteNote is not implemented"))
}

func (UnimplementedNotesServiceHandler) UploadNoteImage(context.Context, *connect.Request[v1.UploadNoteImageRequest]) (*connect.Response[v1.UploadNoteImageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.UploadNoteImage is not implemented"))
}

func (UnimplementedNotesServiceHandler) Search(context.Context, *connect.Request[v1.SearchRequest]) (*connect.Response[v1.SearchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.Search is not implemented"))
}

func (UnimplementedNotesServiceHandler) ShareNote(context.Context, *connect.Request[v1.ShareNoteRequest]) (*connect.Response[v1.ShareNoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.ShareNote is not implemented"))
}

func (UnimplementedNotesServiceHandler) ShareNotebook(context.Context, *connect.Request[v1.ShareNotebookRequest]) (*connect.Response[v1.ShareNotebookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.ShareNotebook is not implemented"))
}

func (UnimplementedNotesServiceHandler) Unshare(context.Context, *connect.Request[v1.UnshareRequest]) (*connect.Response[v1.UnshareResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.Unshare is not implemented"))
}

func (UnimplementedNotesServiceHandler) ListShares(context.Context, *connect.Request[v1.ListSharesRequest]) (*connect.Response[v1.ListSharesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.ListShares is not implemented"))
}

func (UnimplementedNotesServiceHandler) ListSharedWithMe(context.Context, *connect.Request[v1.ListSharedWithMeRequest]) (*connect.Response[v1.ListSharedWithMeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.ListSharedWithMe is not implemented"))
}

func (UnimplementedNotesServiceHandler) AddComment(context.Context, *connect.Request[v1.AddCommentRequest]) (*connect.Response[v1.AddCommentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.AddComment is not implemented"))
}

func (UnimplementedNotesServiceHandler) ListComments(context.Context, *connect.Request[v1.ListCommentsRequest]) (*connect.Response[v1.ListCommentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.ListComments is not implemented"))
}

func (UnimplementedNotesServiceHandler) ResolveComment(context.Context, *connect.Request[v1.ResolveCommentRequest]) (*connect.Response[v1.ResolveCommentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.ResolveComment is not implemented"))
}

func (UnimplementedNotesServiceHandler) ListActivity(context.Context, *connect.Request[v1.ListActivityRequest]) (*connect.Response[v1.ListActivityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notes.v1.NotesService.ListActivity is not implemented"))
}
