// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: notifications/v1/notifications.proto

package notificationsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nnc/family-manager/sdk/go/notifications/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NotificationsServiceName is the fully-qualified name of the NotificationsService service.
	NotificationsServiceName = "notifications.v1.NotificationsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NotificationsServiceRegisterPushTokenProcedure is the fully-qualified name of the
	// NotificationsService's RegisterPushToken RPC.
	NotificationsServiceRegisterPushTokenProcedure = "/notifications.v1.NotificationsService/RegisterPushToken"
	// NotificationsServiceUnregisterPushTokenProcedure is the fully-qualified name of the
	// NotificationsService's UnregisterPushToken RPC.
	NotificationsServiceUnregisterPushTokenProcedure = "/notifications.v1.NotificationsService/UnregisterPushToken"
	// NotificationsServiceGetPreferencesProcedure is the fully-qualified name of the
	// NotificationsService's GetPreferences RPC.
	NotificationsServiceGetPreferencesProcedure = "/notifications.v1.NotificationsService/GetPreferences"
	// NotificationsServiceSetPreferencesProcedure is the fully-qualified name of the
	// NotificationsService's SetPreferences RPC.
	NotificationsServiceSetPreferencesProcedure = "/notifications.v1.NotificationsService/SetPreferences"
)

// NotificationsServiceClient is a client for the notifications.v1.NotificationsService service.
type NotificationsServiceClient interface {
	RegisterPushToken(context.Context, *connect.Request[v1.RegisterPushTokenRequest]) (*connect.Response[v1.RegisterPushTokenResponse], error)
	UnregisterPushToken(context.Context, *connect.Request[v1.UnregisterPushTokenRequest]) (*connect.Response[v1.UnregisterPushTokenResponse], error)
	GetPreferences(context.Context, *connect.Request[v1.GetPreferencesRequest]) (*connect.Response[v1.GetPreferencesResponse], error)
	SetPreferences(context.Context, *connect.Request[v1.SetPreferencesRequest]) (*connect.Response[v1.SetPreferencesResponse], error)
}

// NewNotificationsServiceClient constructs a client for the notifications.v1.NotificationsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNotificationsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NotificationsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	notificationsServiceMethods := v1.File_notifications_v1_notifications_proto.Services().ByName("NotificationsService").Methods()
	return &notificationsServiceClient{
		registerPushToken: connect.NewClient[v1.RegisterPushTokenRequest, v1.RegisterPushTokenResponse](
			httpClient,
			baseURL+NotificationsServiceRegisterPushTokenProcedure,
			connect.WithSchema(notificationsServiceMethods.ByName("RegisterPushToken")),
			connect.WithClientOptions(opts...),
		),
		unregisterPushToken: connect.NewClient[v1.UnregisterPushTokenRequest, v1.UnregisterPushTokenResponse](
			httpClient,
			baseURL+NotificationsServiceUnregisterPushTokenProcedure,
			connect.WithSchema(notificationsServiceMethods.ByName("UnregisterPushToken")),
			connect.WithClientOptions(opts...),
		),
		getPreferences: connect.NewClient[v1.GetPreferencesRequest, v1.GetPreferencesResponse](
			httpClient,
			baseURL+NotificationsServiceGetPreferencesProcedure,
			connect.WithSchema(notificationsServiceMethods.ByName("GetPreferences")),
			connect.WithClientOptions(opts...),
		),
		setPreferences: connect.NewClient[v1.SetPreferencesRequest, v1.SetPreferencesResponse](
			httpClient,
			baseURL+NotificationsServiceSetPreferencesProcedure,
			connect.WithSchema(notificationsServiceMethods.ByName("SetPreferences")),
			connect.WithClientOptions(opts...),
		),
	}
}

// notificationsServiceClient implements NotificationsServiceClient.
type notificationsServiceClient struct {
	registerPushToken   *connect.Client[v1.RegisterPushTokenRequest, v1.RegisterPushTokenResponse]
	unregisterPushToken *connect.Client[v1.UnregisterPushTokenRequest, v1.UnregisterPushTokenResponse]
	getPreferences      *connect.Client[v1.GetPreferencesRequest, v1.GetPreferencesResponse]
	setPreferences      *connect.Client[v1.SetPreferencesRequest, v1.SetPreferencesResponse]
}

// RegisterPushToken calls notifications.v1.NotificationsService.RegisterPushToken.
func (c *notificationsServiceClient) RegisterPushToken(ctx context.Context, req *connect.Request[v1.RegisterPushTokenRequest]) (*connect.Response[v1.RegisterPushTokenResponse], error) {
	return c.registerPushToken.CallUnary(ctx, req)
}

// UnregisterPushToken calls notifications.v1.NotificationsService.UnregisterPushToken.
func (c *notificationsServiceClient) UnregisterPushToken(ctx context.Context, req *connect.Request[v1.UnregisterPushTokenRequest]) (*connect.Response[v1.UnregisterPushTokenResponse], error) {
	return c.unregisterPushToken.CallUnary(ctx, req)
}

// GetPreferences calls notifications.v1.NotificationsService.GetPreferences.
func (c *notificationsServiceClient) GetPreferences(ctx context.Context, req *connect.Request[v1.GetPreferencesRequest]) (*connect.Response[v1.GetPreferencesResponse], error) {
	return c.getPreferences.CallUnary(ctx, req)
}

// SetPreferences calls notifications.v1.NotificationsService.SetPreferences.
func (c *notificationsServiceClient) SetPreferences(ctx context.Context, req *connect.Request[v1.SetPreferencesRequest]) (*connect.Response[v1.SetPreferencesResponse], error) {
	return c.setPreferences.CallUnary(ctx, req)
}

// NotificationsServiceHandler is an implementation of the notifications.v1.NotificationsService
// service.
type NotificationsServiceHandler interface {
	RegisterPushToken(context.Context, *connect.Request[v1.RegisterPushTokenRequest]) (*connect.Response[v1.RegisterPushTokenResponse], error)
	UnregisterPushToken(context.Context, *connect.Request[v1.UnregisterPushTokenRequest]) (*connect.Response[v1.UnregisterPushTokenResponse], error)
	GetPreferences(context.Context, *connect.Request[v1.GetPreferencesRequest]) (*connect.Response[v1.GetPreferencesResponse], error)
	SetPreferences(context.Context, *connect.Request[v1.SetPreferencesRequest]) (*connect.Response[v1.SetPreferencesResponse], error)
}

// NewNotificationsServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNotificationsServiceHandler(svc NotificationsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	notificationsServiceMethods := v1.File_notifications_v1_notifications_proto.Services().ByName("NotificationsService").Methods()
	notificationsServiceRegisterPushTokenHandler := connect.NewUnaryHandler(
		NotificationsServiceRegisterPushTokenProcedure,
		svc.RegisterPushToken,
		connect.WithSchema(notificationsServiceMethods.ByName("RegisterPushToken")),
		connect.WithHandlerOptions(opts...),
	)
	notificationsServiceUnregisterPushTokenHandler := connect.NewUnaryHandler(
		NotificationsServiceUnregisterPushTokenProcedure,
		svc.UnregisterPushToken,
		connect.WithSchema(notificationsServiceMethods.ByName("UnregisterPushToken")),
		connect.WithHandlerOptions(opts...),
	)
	notificationsServiceGetPreferencesHandler := connect.NewUnaryHandler(
		NotificationsServiceGetPreferencesProcedure,
		svc.GetPreferences,
		connect.WithSchema(notificationsServiceMethods.ByName("GetPreferences")),
		connect.WithHandlerOptions(opts...),
	)
	notificationsServiceSetPreferencesHandler := connect.NewUnaryHandler(
		NotificationsServiceSetPreferencesProcedure,
		svc.SetPreferences,
		connect.WithSchema(notificationsServiceMethods.ByName("SetPreferences")),
		connect.WithHandlerOptions(opts...),
	)
	return "/notifications.v1.NotificationsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NotificationsServiceRegisterPushTokenProcedure:
			notificationsServiceRegisterPushTokenHandler.ServeHTTP(w, r)
		case NotificationsServiceUnregisterPushTokenProcedure:
			notificationsServiceUnregisterPushTokenHandler.ServeHTTP(w, r)
		case NotificationsServiceGetPreferencesProcedure:
			notificationsServiceGetPreferencesHandler.ServeHTTP(w, r)
		case NotificationsServiceSetPreferencesProcedure:
			notificationsServiceSetPreferencesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNotificationsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNotificationsServiceHandler struct{}

func (UnimplementedNotificationsServiceHandler) RegisterPushToken(context.Context, *connect.Request[v1.RegisterPushTokenRequest]) (*connect.Response[v1.RegisterPushTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notifications.v1.NotificationsService.RegisterPushToken is not implemented"))
}

func (UnimplementedNotificationsServiceHandler) UnregisterPushToken(context.Context, *connect.Request[v1.UnregisterPushTokenRequest]) (*connect.Response[v1.UnregisterPushTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notifications.v1.NotificationsService.UnregisterPushToken is not implemented"))
}

func (UnimplementedNotificationsServiceHandler) GetPreferences(context.Context, *connect.Request[v1.GetPreferencesRequest]) (*connect.Response[v1.GetPreferencesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notifications.v1.NotificationsService.GetPreferences is not implemented"))
}

func (UnimplementedNotificationsServiceHandler) SetPreferences(context.Context, *connect.Request[v1.SetPreferencesRequest]) (*connect.Response[v1.SetPreferencesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("notifications.v1.NotificationsService.SetPreferences is not implemented"))
}
